In [1]:
library(tidyverse)
library(data.table)
library(purrr)

-- Attaching core tidyverse packages ---------------------------------------------------------------- tidyverse 2.0.0 --
v dplyr     1.1.2     v readr     2.1.4
v forcats   1.0.0     v stringr   1.5.0
v ggplot2   3.4.3     v tibble    3.2.1
v lubridate 1.9.2     v tidyr     1.3.0
v purrr     1.0.1
-- Conflicts ---------------------------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: 'data.table'


The following objects are masked from 'package:lubridate':

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from 'package:dplyr':

    between, first, last


The following object is masked from 'package:purrr':

    transpose

In [2]:
tab <- fread("../no prunning/no_pruning.csv")
tab <- tab[,14:(ncol(tab) - 1)]

In [107]:
col_list  <- as.list(colnames(tab)) %>% 
    map(., ~str_replace(.x, ".*_", ""))
length(col_list)

[1] 302

In [4]:
for (rs in col_list) {
   cat(rs, '\n')
}

#the below list is copied and pasted into VEP web interface

rs4713859
rs3736228
rs10476909
rs1379544
rs921978
rs447950
rs414582
rs3733658
rs2400891
rs10062536
rs4988300
rs4713858
rs1363629
rs6861564
rs4713854
rs7728256
rs452366
rs474742
rs476741
rs241280
rs2454104
rs3823434
rs312009
rs314750
rs3781586
rs3781590
rs634008
rs4409073
rs6887452
rs353237
rs10061434
rs599083
rs12417014
rs12659504
rs2306862
rs7936582
rs17724303
rs11826287
rs2267665
rs1883322
rs632605
rs116213531
rs75210709
rs2508835
rs72823547
rs11228270
rs353294
rs115128769
rs11574424
rs660925
rs115658620
rs77381812
rs2125130
rs72936563
rs2895862
rs353248
rs6861618
rs78578633
rs74724919
rs62378023
rs118098503
rs353241
rs111416523
rs4988332
rs35388122
rs113800014
rs6894391
rs72932379
rs117311236
rs35928487
rs114688286
rs62378010
rs6889482
rs4988321
rs118062233
rs77489920
rs13214733
rs72823546
rs10454990
rs76225083
rs75177427
rs7342161
rs74474766
rs11228184
rs75148296
rs115413638
rs57928864
rs74697984
rs4705346
rs55915030
rs111489476
rs118050745
rs353243
rs11602367
rs76710454
rs3802746
rs75777785
rs73279543
rs2016520
rs11745684
rs1003973
rs1887490
rs2479131
rs3827743
rs3798343
rs4847017
rs11122576
rs12038826
rs6661547
rs12731961
rs853463
rs11122577
rs6457816
rs4847000
rs6677009
rs7761870
rs2395626
rs12203818
rs2067853
rs5051
rs3734254
rs6698654
rs9462081
rs6457821
rs3800376
rs7769417
rs853464
rs853469
rs6541330
rs3789647
rs12031571
rs4259658
rs1316409
rs12082061
rs1316408
rs12084401
rs2493151
rs699
rs9658119
rs872505
rs2228265
rs2182574
rs3789643
rs9368868
rs6911817
rs41270076
rs6919534
rs72759029
rs9462088
rs111776064
rs11586594
rs77645389
rs76626846
rs9658130
rs2297831
rs115269427
rs72894770
rs9658058
rs28359664
rs11751895
rs74792490
rs9658105
rs7758272
rs34474204
rs41314282
rs3790973
rs67056409
rs6907678
rs112012380
rs11122597
rs35080860
rs7771323
rs79722771
rs6937510
rs5049
rs61828616
rs78869074
rs78983929
rs4713872
rs943581
rs3823433
rs7744392
rs72911076
rs7770619
rs28359599
rs2493153
rs4713871
rs2395617
rs74143000
rs11568048
rs10947541
rs6910489
rs72759021
rs12525006
rs6927367
rs6934083
rs11553984
rs10158163
rs78945013
rs6457813
rs9658134
rs2296802
rs2564929
rs4846997
rs3761041
rs1080500
rs372889
rs13088281
rs2564921
rs6770152
rs1483185
rs7079
rs3730179
rs4687712
rs4687717
rs172043
rs271828
rs874628
rs12632671
rs16982285
rs8108738
rs11666281
rs4328795
rs11122563
rs28359608
rs2305743
rs11130350
rs375947
rs438421
rs13085294
rs11122562
rs740691
rs13433700
rs999813
rs4762
rs73076230
rs10433616
rs17885285
rs3889728
rs17886368
rs17879591
rs2049051
rs117329793
rs7630325
rs2336725
rs3761951
rs28359615
rs28359647
rs77000231
rs75323042
rs28359725
rs115659375
rs73001430
rs7552686
rs11710524
rs79430272
rs28359708
rs4687718
rs116656058
rs2072490
rs10425001
rs11924565
rs73091425
rs11554159
rs2581830
rs10411949
rs729396
rs3790960
rs62120394
rs114058530
rs271834
rs7610701
rs62120362
rs6687027
rs412133
rs10864772
rs56020911
rs79843306
rs11919522
rs114139529
rs11717712
rs13316641
rs12462974
rs3803919
rs115657945
rs2493131
rs6799185
rs112011964
rs116071986
rs117648604
rs111501004
rs11670370
rs4808770
rs17733009
rs436857
rs56022120
rs79268593
rs11558606
rs62255930
rs61740749
rs750527
rs1004807

#### Function to clean marker names

In [85]:
clean_marker <- function(marker) {
  marker <- tolower(marker)
  marker <- gsub("gsa-|seq-", "", marker)
  marker <- dplyr::recode(marker, "ilmnseq_6:35378798" = "rs9658134")
  return(marker)
}

In [114]:
snp <- fread("../feature_tsv/ancestry_allele_frequency/plink.assoc.logistic.tsv") %>%
  filter(TEST == "ADD") %>%   
  mutate(SNP = clean_marker(SNP)) %>% 
  select(c(SNP, ORX, A1, P )) %>% 
  rename(allele = A1, marker = SNP, OR = ORX) %>% 
  filter(marker %in% col_list)

In [123]:
vep <- fread("./vep_output/vep_output.txt", sep="\t")

In [121]:
setdiff(col_list, snp$marker )

[[1]]
[1] "rs72932379"

[[2]]
[1] "rs72823546"

[[3]]
[1] "rs75177427"

[[4]]
[1] "rs7761870"

[[5]]
[1] "rs6457821"

[[6]]
[1] "rs111776064"

[[7]]
[1] "rs3823433"

[[8]]
[1] "rs6457813"

[[9]]
[1] "rs9658134"

In [124]:
vep <- vep %>% 
    rename(marker = `#Uploaded_variation`, allele = Allele, consequence = Consequence , impact = IMPACT, symbol = SYMBOL, biotype = BIOTYPE, `CADD_phred` = `CADD_PHRED`, Canonical = CANONICAL) #%>% 
#     select(c(marker, allele, symbol, consequence, impact, biotype, Feature_type, Feature, `CADD_phred`, Canonical, AF, AFR_AF, AMR_AF, EAS_AF, EUR_AF, SAS_AF) )

In [135]:
combined <- vep %>% 
left_join(snp, by= c("marker", "allele")) %>% 
arrange(P) %>% 
mutate(P = round(P, 3)) %>% 
distinct()

combined$EXON <- as.character(combined$EXON)
combined$INTRON <- as.character(combined$INTRON)

In [136]:
combined

     marker      Location                      allele
1    rs12731961  1:230923313-230923313         T
2    rs12731961  1:230923313-230923313         T
3    rs12731961  1:230923313-230923313         T
4    rs12731961  1:230923313-230923313         T
5    rs12731961  1:230923313-230923313         T
6    rs12731961  1:230923313-230923313         T
7    rs12731961  1:230923313-230923313         T
8    rs12082061  1:230924905-230924905         T
9    rs12082061  1:230924905-230924905         T
10   rs12082061  1:230924905-230924905         T
11   rs12082061  1:230924905-230924905         T
12   rs12082061  1:230924905-230924905         T
13   rs12082061  1:230924905-230924905         T
14   rs12082061  1:230924905-230924905         T
15   rs2454104   5:148821990-148821990         A
16   rs2454104   5:148821990-148821990         A
17   rs2454104   5:148821990-148821990         A
18   rs11228184  11:68025850-68025850          A
19   rs11228184  11:68025850-68025850          A
20   rs11228184  11:68025850-68025850          A
21   rs11228184  11:68025850-68025850          A
22   rs729396    3:53228342-53228342           T
23   rs729396    3:53228342-53228342           T
24   rs729396    HG957_PATCH:53228342-53228342 T
25   rs729396    HG957_PATCH:53228342-53228342 T
26   rs79722771  6:35469050-35469050           T
27   rs79722771  6:35469050-35469050           T
28   rs79722771  6:35469050-35469050           T
29   rs79722771  6:35469050-35469050           T
30   rs79722771  6:35469050-35469050           T
...  ...         ...                           ...
2271 rs4687718   HG957_PATCH:53282303-53282303 T
2272 rs4687718   HG957_PATCH:53282303-53282303 G
2273 rs4687718   HG957_PATCH:53282303-53282303 T
2274 rs4687718   HG957_PATCH:53282303-53282303 G
2275 rs4687718   HG957_PATCH:53282303-53282303 T
2276 rs10433616  HG957_PATCH:53284363-53284363 A
2277 rs10433616  HG957_PATCH:53284363-53284363 G
2278 rs10433616  HG957_PATCH:53284363-53284363 T
2279 rs10433616  HG957_PATCH:53284363-53284363 A
2280 rs10433616  HG957_PATCH:53284363-53284363 G
2281 rs10433616  HG957_PATCH:53284363-53284363 T
2282 rs10433616  HG957_PATCH:53284363-53284363 A
2283 rs10433616  HG957_PATCH:53284363-53284363 G
2284 rs10433616  HG957_PATCH:53284363-53284363 T
2285 rs10433616  HG957_PATCH:53284363-53284363 A
2286 rs10433616  HG957_PATCH:53284363-53284363 G
2287 rs10433616  HG957_PATCH:53284363-53284363 T
2288 rs10433616  HG957_PATCH:53284363-53284363 A
2289 rs10433616  HG957_PATCH:53284363-53284363 G
2290 rs10433616  HG957_PATCH:53284363-53284363 T
2291 rs10433616  HG957_PATCH:53284363-53284363 A
2292 rs10433616  HG957_PATCH:53284363-53284363 G
2293 rs10433616  HG957_PATCH:53284363-53284363 T
2294 rs10433616  HG957_PATCH:53284363-53284363 A
2295 rs10433616  HG957_PATCH:53284363-53284363 G
2296 rs10433616  HG957_PATCH:53284363-53284363 T
2297 rs10433616  HG957_PATCH:53284363-53284363 A
2298 rs10433616  HG957_PATCH:53284363-53284363 G
2299 rs10433616  HG957_PATCH:53284363-53284363 T
2300 rs115659375 HG957_PATCH:53303906-53303906 T
     consequence                                  impact   symbol
1    missense_variant                             MODERATE CAPN9
2    missense_variant                             MODERATE CAPN9
3    missense_variant                             MODERATE CAPN9
4    intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
5    intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
6    intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
7    upstream_gene_variant                        MODIFIER CAPN9
8    intron_variant                               MODIFIER CAPN9
9    intron_variant                               MODIFIER CAPN9
10   intron_variant                               MODIFIER CAPN9
11   intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
12   intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
13   intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
14   upstream_gene_variant                        MODIFIER CAPN9
15   regulatory_region_variant                    MODIFIER -
16   TF_binding_site_variant                      MODIFIER -
17   intergenic_variant                           MODIFIER -
18   downstream_gene_variant                      MODIFIER C11orf24
19   downstream_gene_variant                      MODIFIER C11orf24
20   downstream_gene_variant                      MODIFIER C11orf24
21   downstream_gene_variant                      MODIFIER C11orf24
22   downstream_gene_variant                      MODIFIER PRKCD
23   downstream_gene_variant                      MODIFIER PRKCD
24   downstream_gene_variant                      MODIFIER PRKCD
25   downstream_gene_variant                      MODIFIER PRKCD
26   intron_variant                               MODIFIER TULP1
27   intron_variant                               MODIFIER TULP1
28   upstream_gene_variant                        MODIFIER TEAD3
29   downstream_gene_variant                      MODIFIER TULP1
30   upstream_gene_variant                        MODIFIER TEAD3
...  ...                                          ...      ...
2271 intron_variant                               MODIFIER TKT
2272 intron_variant,NMD_transcript_variant        MODIFIER TKT
2273 intron_variant,NMD_transcript_variant        MODIFIER TKT
2274 intron_variant,NMD_transcript_variant        MODIFIER TKT
2275 intron_variant,NMD_transcript_variant        MODIFIER TKT
2276 intron_variant,NMD_transcript_variant        MODIFIER TKT
2277 intron_variant,NMD_transcript_variant        MODIFIER TKT
2278 intron_variant,NMD_transcript_variant        MODIFIER TKT
2279 intron_variant                               MODIFIER TKT
2280 intron_variant                               MODIFIER TKT
2281 intron_variant                               MODIFIER TKT
2282 intron_variant                               MODIFIER TKT
2283 intron_variant                               MODIFIER TKT
2284 intron_variant                               MODIFIER TKT
2285 intron_variant                               MODIFIER TKT
2286 intron_variant                               MODIFIER TKT
2287 intron_variant                               MODIFIER TKT
2288 intron_variant,non_coding_transcript_variant MODIFIER TKT
2289 intron_variant,non_coding_transcript_variant MODIFIER TKT
2290 intron_variant,non_coding_transcript_variant MODIFIER TKT
2291 intron_variant                               MODIFIER TKT
2292 intron_variant                               MODIFIER TKT
2293 intron_variant                               MODIFIER TKT
2294 intron_variant,NMD_transcript_variant        MODIFIER TKT
2295 intron_variant,NMD_transcript_variant        MODIFIER TKT
2296 intron_variant,NMD_transcript_variant        MODIFIER TKT
2297 intron_variant,NMD_transcript_variant        MODIFIER TKT
2298 intron_variant,NMD_transcript_variant        MODIFIER TKT
2299 intron_variant,NMD_transcript_variant        MODIFIER TKT
2300 intergenic_variant                           MODIFIER -
     Gene            Feature_type      Feature
1    ENSG00000135773 Transcript        ENST00000271971.2
2    ENSG00000135773 Transcript        ENST00000354537.1
3    ENSG00000135773 Transcript        ENST00000366666.2
4    ENSG00000244137 Transcript        ENST00000412344.1
5    ENSG00000244137 Transcript        ENST00000428480.1
6    ENSG00000244137 Transcript        ENST00000452640.1
7    ENSG00000135773 Transcript        ENST00000480004.1
8    ENSG00000135773 Transcript        ENST00000271971.2
9    ENSG00000135773 Transcript        ENST00000354537.1
10   ENSG00000135773 Transcript        ENST00000366666.2
11   ENSG00000244137 Transcript        ENST00000412344.1
12   ENSG00000244137 Transcript        ENST00000428480.1
13   ENSG00000244137 Transcript        ENST00000452640.1
14   ENSG00000135773 Transcript        ENST00000480004.1
15   -               RegulatoryFeature ENSR00000317877
16   -               MotifFeature      ENSM00527917318
17   -               -                 -
18   ENSG00000171067 Transcript        ENST00000304271.6
19   ENSG00000171067 Transcript        ENST00000530166.1
20   ENSG00000171067 Transcript        ENST00000531745.1
21   ENSG00000171067 Transcript        ENST00000533310.1
22   ENSG00000163932 Transcript        ENST00000330452.3
23   ENSG00000163932 Transcript        ENST00000394729.2
24   ENSG00000273482 Transcript        ENST00000608339.1
25   ENSG00000273482 Transcript        ENST00000608438.1
26   ENSG00000112041 Transcript        ENST00000229771.6
27   ENSG00000112041 Transcript        ENST00000322263.4
28   ENSG00000007866 Transcript        ENST00000338863.7
29   ENSG00000112041 Transcript        ENST00000373892.4
30   ENSG00000007866 Transcript        ENST00000402886.3
...  ...             ...               ...
2271 ENSG00000272687 Transcript        ENST00000609496.1
2272 ENSG00000272687 Transcript        ENST00000609624.1
2273 ENSG00000272687 Transcript        ENST00000609624.1
2274 ENSG00000272687 Transcript        ENST00000610176.1
2275 ENSG00000272687 Transcript        ENST00000610176.1
2276 ENSG00000272687 Transcript        ENST00000608285.1
2277 ENSG00000272687 Transcript        ENST00000608285.1
2278 ENSG00000272687 Transcript        ENST00000608285.1
2279 ENSG00000272687 Transcript        ENST00000608398.1
2280 ENSG00000272687 Transcript        ENST00000608398.1
2281 ENSG00000272687 Transcript        ENST00000608398.1
2282 ENSG00000272687 Transcript        ENST00000608828.1
2283 ENSG00000272687 Transcript        ENST00000608828.1
2284 ENSG00000272687 Transcript        ENST00000608828.1
2285 ENSG00000272687 Transcript        ENST00000609357.1
2286 ENSG00000272687 Transcript        ENST00000609357.1
2287 ENSG00000272687 Transcript        ENST00000609357.1
2288 ENSG00000272687 Transcript        ENST00000609397.1
2289 ENSG00000272687 Transcript        ENST00000609397.1
2290 ENSG00000272687 Transcript        ENST00000609397.1
2291 ENSG00000272687 Transcript        ENST00000609496.1
2292 ENSG00000272687 Transcript        ENST00000609496.1
2293 ENSG00000272687 Transcript        ENST00000609496.1
2294 ENSG00000272687 Transcript        ENST00000609624.1
2295 ENSG00000272687 Transcript        ENST00000609624.1
2296 ENSG00000272687 Transcript        ENST00000609624.1
2297 ENSG00000272687 Transcript        ENST00000610176.1
2298 ENSG00000272687 Transcript        ENST00000610176.1
2299 ENSG00000272687 Transcript        ENST00000610176.1
2300 -               -                 -
     biotype                 ... TRANSCRIPTION_FACTORS
1    protein_coding          ... -
2    protein_coding          ... -
3    protein_coding          ... -
4    antisense               ... -
5    antisense               ... -
6    antisense               ... -
7    processed_transcript    ... -
8    protein_coding          ... -
9    protein_coding          ... -
10   protein_coding          ... -
11   antisense               ... -
12   antisense               ... -
13   antisense               ... -
14   processed_transcript    ... -
15   CTCF_binding_site       ... -
16   -                       ... ELK1::SREBF2
17   -                       ... -
18   protein_coding          ... -
19   processed_transcript    ... -
20   processed_transcript    ... -
21   protein_coding          ... -
22   protein_coding          ... -
23   protein_coding          ... -
24   protein_coding          ... -
25   protein_coding          ... -
26   protein_coding          ... -
27   protein_coding          ... -
28   protein_coding          ... -
29   retained_intron         ... -
30   protein_coding          ... -
...  ...                         ...
2271 protein_coding          ... -
2272 nonsense_mediated_decay ... -
2273 nonsense_mediated_decay ... -
2274 nonsense_mediated_decay ... -
2275 nonsense_mediated_decay ... -
2276 nonsense_mediated_decay ... -
2277 nonsense_mediated_decay ... -
2278 nonsense_mediated_decay ... -
2279 protein_coding          ... -
2280 protein_coding          ... -
2281 protein_coding          ... -
2282 protein_coding          ... -
2283 protein_coding          ... -
2284 protein_coding          ... -
2285 protein_coding          ... -
2286 protein_coding          ... -
2287 protein_coding          ... -
2288 retained_intron         ... -
2289 retained_intron         ... -
2290 retained_intron         ... -
2291 protein_coding          ... -
2292 protein_coding          ... -
2293 protein_coding          ... -
2294 nonsense_mediated_decay ... -
2295 nonsense_mediated_decay ... -
2296 nonsense_mediated_decay ... -
2297 nonsense_mediated_decay ... -
2298 nonsense_mediated_decay ... -
2299 nonsense_mediated_decay ... -
2300 -                       ... -
     GO
1    GO:0004198:calcium-dependent_cysteine-type_endopeptidase_activity,GO:0005509:calcium_ion_binding,GO:0005575:cellular_component,GO:0005622:intracellular,GO:0006508:proteolysis,GO:0007586:digestion
2    GO:0004198:calcium-dependent_cysteine-type_endopeptidase_activity,GO:0005509:calcium_ion_binding,GO:0005575:cellular_component,GO:0005622:intracellular,GO:0006508:proteolysis,GO:0007586:digestion
3    GO:0004198:calcium-dependent_cysteine-type_endopeptidase_activity,GO:0005509:calcium_ion_binding,GO:0005622:intracellular,GO:0006508:proteolysis
4    -
5    -
6    -
7    -
8    GO:0004198:calcium-dependent_cysteine-type_endopeptidase_activity,GO:0005509:calcium_ion_binding,GO:0005575:cellular_component,GO:0005622:intracellular,GO:0006508:proteolysis,GO:0007586:digestion
9    GO:0004198:calcium-dependent_cysteine-type_endopeptidase_activity,GO:0005509:calcium_ion_binding,GO:0005575:cellular_component,GO:0005622:intracellular,GO:0006508:proteolysis,GO:0007586:digestion
10   GO:0004198:calcium-dependent_cysteine-type_endopeptidase_activity,GO:0005509:calcium_ion_binding,GO:0005622:intracellular,GO:0006508:proteolysis
11   -
12   -
13   -
14   -
15   -
16   -
17   -
18   GO:0016021:integral_component_of_membrane
19   -
20   -
21   -
22   GO:0001666:response_to_hypoxia,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0004697:protein_kinase_C_activity,GO:0004699:calcium-independent_protein_kinase_C_activity,GO:0004713:protein_tyrosine_kinase_activity,GO:0004715:non-membrane_spanning_protein_tyrosine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005634:nucleus,GO:0005654:nucleoplasm,GO:0005737:cytoplasm,GO:0005739:mitochondrion,GO:0005783:endoplasmic_reticulum,GO:0005829:cytosol,GO:0005886:plasma_membrane,GO:0005911:cell-cell_junction,GO:0006468:protein_phosphorylation,GO:0006915:apoptotic_process,GO:0006921:cellular_component_disassembly_involved_in_execution_phase_of_apoptosis,GO:0007049:cell_cycle,GO:0007165:signal_transduction,GO:0007173:epidermal_growth_factor_receptor_signaling_pathway,GO:0007202:activation_of_phospholipase_C_activity,GO:0007568:aging,GO:0007596:blood_coagulation,GO:0008022:protein_C-terminus_binding,GO:0008047:enzyme_activator_activity,GO:0008543:fibroblast_growth_factor_receptor_signaling_pathway,GO:0009408:response_to_heat,GO:0009612:response_to_mechanical_stimulus,GO:0009749:response_to_glucose,GO:0010467:gene_expression,GO:0010469:regulation_of_receptor_activity,GO:0014070:response_to_organic_cyclic_compound,GO:0015810:aspartate_transport,GO:0016064:immunoglobulin_mediated_immune_response,GO:0016070:RNA_metabolic_process,GO:0016071:mRNA_metabolic_process,GO:0016363:nuclear_matrix,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups,GO:0018107:peptidyl-threonine_phosphorylation,GO:0019221:cytokine-mediated_signaling_pathway,GO:0019899:enzyme_binding,GO:0019901:protein_kinase_binding,GO:0023021:termination_of_signal_transduction,GO:0030168:platelet_activation,GO:0030837:negative_regulation_of_actin_filament_polymerization,GO:0032091:negative_regulation_of_protein_binding,GO:0032613:interleukin-10_production,GO:0032615:interleukin-12_production,GO:0032869:cellular_response_to_insulin_stimulus,GO:0032930:positive_regulation_of_superoxide_anion_generation,GO:0032963:collagen_metabolic_process,GO:0034351:negative_regulation_of_glial_cell_apoptotic_process,GO:0035307:positive_regulation_of_protein_dephosphorylation,GO:0035556:intracellular_signal_transduction,GO:0038096:Fc-gamma_receptor_signaling_pathway_involved_in_phagocytosis,GO:0042100:B_cell_proliferation,GO:0042119:neutrophil_activation,GO:0042149:cellular_response_to_glucose_starvation,GO:0042493:response_to_drug,GO:0042542:response_to_hydrogen_peroxide,GO:0042742:defense_response_to_bacterium,GO:0043065:positive_regulation_of_apoptotic_process,GO:0043200:response_to_amino_acid,GO:0043406:positive_regulation_of_MAP_kinase_activity,GO:0043407:negative_regulation_of_MAP_kinase_activity,GO:0043560:insulin_receptor_substrate_binding,GO:0045087:innate_immune_response,GO:0045471:response_to_ethanol,GO:0046326:positive_regulation_of_glucose_import,GO:0046627:negative_regulation_of_insulin_receptor_signaling_pathway,GO:0046777:protein_autophosphorylation,GO:0046872:metal_ion_binding,GO:0048011:neurotrophin_TRK_receptor_signaling_pathway,GO:0048471:perinuclear_region_of_cytoplasm,GO:0050728:negative_regulation_of_inflammatory_response,GO:0050732:negative_regulation_of_peptidyl-tyrosine_phosphorylation,GO:0050821:protein_stabilization,GO:0051490:negative_regulation_of_filopodium_assembly,GO:0060333:interferon-gamma-mediated_signaling_pathway,GO:0070976:TIR_domain_binding,GO:0090331:negative_regulation_of_platelet_aggregation,GO:0090398:cellular_senescence,GO:1900163:positive_regulation_of_phospholipid_scramblase_activity,GO:2000304:positive_regulation_of_ceramide_biosynthetic_process,GO:2000753:positive_regulation_of_glucosylceramide_catabolic_process,GO:2000755:positive_regulation_of_sphingomyelin_catabolic_process,GO:2001022:positive_regulation_of_response_to_DNA_damage_stimulus

In [138]:
rank <- fread("./xgboost_output_feature_importance")  %>% 
    rename(variant = V1, xgboost_score = V2) %>% 
    mutate(variant = clean_marker(variant)) %>% 
    filter(grepl("rs", variant)) %>% 
    separate(variant, into = c("gene", "marker"), sep = "_")  %>% 
    arrange(desc(xgboost_score)) %>% 
    filter(xgboost_score != 0 )

In [148]:
withUnpruned <- left_join(combined, rank, by="marker") %>% 
distinct()

In [149]:
withUnpruned

     marker      Location                      allele
1    rs12731961  1:230923313-230923313         T
2    rs12731961  1:230923313-230923313         T
3    rs12731961  1:230923313-230923313         T
4    rs12731961  1:230923313-230923313         T
5    rs12731961  1:230923313-230923313         T
6    rs12731961  1:230923313-230923313         T
7    rs12731961  1:230923313-230923313         T
8    rs12082061  1:230924905-230924905         T
9    rs12082061  1:230924905-230924905         T
10   rs12082061  1:230924905-230924905         T
11   rs12082061  1:230924905-230924905         T
12   rs12082061  1:230924905-230924905         T
13   rs12082061  1:230924905-230924905         T
14   rs12082061  1:230924905-230924905         T
15   rs2454104   5:148821990-148821990         A
16   rs2454104   5:148821990-148821990         A
17   rs2454104   5:148821990-148821990         A
18   rs11228184  11:68025850-68025850          A
19   rs11228184  11:68025850-68025850          A
20   rs11228184  11:68025850-68025850          A
21   rs11228184  11:68025850-68025850          A
22   rs729396    3:53228342-53228342           T
23   rs729396    3:53228342-53228342           T
24   rs729396    HG957_PATCH:53228342-53228342 T
25   rs729396    HG957_PATCH:53228342-53228342 T
26   rs79722771  6:35469050-35469050           T
27   rs79722771  6:35469050-35469050           T
28   rs79722771  6:35469050-35469050           T
29   rs79722771  6:35469050-35469050           T
30   rs79722771  6:35469050-35469050           T
...  ...         ...                           ...
2271 rs4687718   HG957_PATCH:53282303-53282303 T
2272 rs4687718   HG957_PATCH:53282303-53282303 G
2273 rs4687718   HG957_PATCH:53282303-53282303 T
2274 rs4687718   HG957_PATCH:53282303-53282303 G
2275 rs4687718   HG957_PATCH:53282303-53282303 T
2276 rs10433616  HG957_PATCH:53284363-53284363 A
2277 rs10433616  HG957_PATCH:53284363-53284363 G
2278 rs10433616  HG957_PATCH:53284363-53284363 T
2279 rs10433616  HG957_PATCH:53284363-53284363 A
2280 rs10433616  HG957_PATCH:53284363-53284363 G
2281 rs10433616  HG957_PATCH:53284363-53284363 T
2282 rs10433616  HG957_PATCH:53284363-53284363 A
2283 rs10433616  HG957_PATCH:53284363-53284363 G
2284 rs10433616  HG957_PATCH:53284363-53284363 T
2285 rs10433616  HG957_PATCH:53284363-53284363 A
2286 rs10433616  HG957_PATCH:53284363-53284363 G
2287 rs10433616  HG957_PATCH:53284363-53284363 T
2288 rs10433616  HG957_PATCH:53284363-53284363 A
2289 rs10433616  HG957_PATCH:53284363-53284363 G
2290 rs10433616  HG957_PATCH:53284363-53284363 T
2291 rs10433616  HG957_PATCH:53284363-53284363 A
2292 rs10433616  HG957_PATCH:53284363-53284363 G
2293 rs10433616  HG957_PATCH:53284363-53284363 T
2294 rs10433616  HG957_PATCH:53284363-53284363 A
2295 rs10433616  HG957_PATCH:53284363-53284363 G
2296 rs10433616  HG957_PATCH:53284363-53284363 T
2297 rs10433616  HG957_PATCH:53284363-53284363 A
2298 rs10433616  HG957_PATCH:53284363-53284363 G
2299 rs10433616  HG957_PATCH:53284363-53284363 T
2300 rs115659375 HG957_PATCH:53303906-53303906 T
     consequence                                  impact   symbol
1    missense_variant                             MODERATE CAPN9
2    missense_variant                             MODERATE CAPN9
3    missense_variant                             MODERATE CAPN9
4    intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
5    intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
6    intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
7    upstream_gene_variant                        MODIFIER CAPN9
8    intron_variant                               MODIFIER CAPN9
9    intron_variant                               MODIFIER CAPN9
10   intron_variant                               MODIFIER CAPN9
11   intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
12   intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
13   intron_variant,non_coding_transcript_variant MODIFIER RP11-99J16__A.2
14   upstream_gene_variant                        MODIFIER CAPN9
15   regulatory_region_variant                    MODIFIER -
16   TF_binding_site_variant                      MODIFIER -
17   intergenic_variant                           MODIFIER -
18   downstream_gene_variant                      MODIFIER C11orf24
19   downstream_gene_variant                      MODIFIER C11orf24
20   downstream_gene_variant                      MODIFIER C11orf24
21   downstream_gene_variant                      MODIFIER C11orf24
22   downstream_gene_variant                      MODIFIER PRKCD
23   downstream_gene_variant                      MODIFIER PRKCD
24   downstream_gene_variant                      MODIFIER PRKCD
25   downstream_gene_variant                      MODIFIER PRKCD
26   intron_variant                               MODIFIER TULP1
27   intron_variant                               MODIFIER TULP1
28   upstream_gene_variant                        MODIFIER TEAD3
29   downstream_gene_variant                      MODIFIER TULP1
30   upstream_gene_variant                        MODIFIER TEAD3
...  ...                                          ...      ...
2271 intron_variant                               MODIFIER TKT
2272 intron_variant,NMD_transcript_variant        MODIFIER TKT
2273 intron_variant,NMD_transcript_variant        MODIFIER TKT
2274 intron_variant,NMD_transcript_variant        MODIFIER TKT
2275 intron_variant,NMD_transcript_variant        MODIFIER TKT
2276 intron_variant,NMD_transcript_variant        MODIFIER TKT
2277 intron_variant,NMD_transcript_variant        MODIFIER TKT
2278 intron_variant,NMD_transcript_variant        MODIFIER TKT
2279 intron_variant                               MODIFIER TKT
2280 intron_variant                               MODIFIER TKT
2281 intron_variant                               MODIFIER TKT
2282 intron_variant                               MODIFIER TKT
2283 intron_variant                               MODIFIER TKT
2284 intron_variant                               MODIFIER TKT
2285 intron_variant                               MODIFIER TKT
2286 intron_variant                               MODIFIER TKT
2287 intron_variant                               MODIFIER TKT
2288 intron_variant,non_coding_transcript_variant MODIFIER TKT
2289 intron_variant,non_coding_transcript_variant MODIFIER TKT
2290 intron_variant,non_coding_transcript_variant MODIFIER TKT
2291 intron_variant                               MODIFIER TKT
2292 intron_variant                               MODIFIER TKT
2293 intron_variant                               MODIFIER TKT
2294 intron_variant,NMD_transcript_variant        MODIFIER TKT
2295 intron_variant,NMD_transcript_variant        MODIFIER TKT
2296 intron_variant,NMD_transcript_variant        MODIFIER TKT
2297 intron_variant,NMD_transcript_variant        MODIFIER TKT
2298 intron_variant,NMD_transcript_variant        MODIFIER TKT
2299 intron_variant,NMD_transcript_variant        MODIFIER TKT
2300 intergenic_variant                           MODIFIER -
     Gene            Feature_type      Feature
1    ENSG00000135773 Transcript        ENST00000271971.2
2    ENSG00000135773 Transcript        ENST00000354537.1
3    ENSG00000135773 Transcript        ENST00000366666.2
4    ENSG00000244137 Transcript        ENST00000412344.1
5    ENSG00000244137 Transcript        ENST00000428480.1
6    ENSG00000244137 Transcript        ENST00000452640.1
7    ENSG00000135773 Transcript        ENST00000480004.1
8    ENSG00000135773 Transcript        ENST00000271971.2
9    ENSG00000135773 Transcript        ENST00000354537.1
10   ENSG00000135773 Transcript        ENST00000366666.2
11   ENSG00000244137 Transcript        ENST00000412344.1
12   ENSG00000244137 Transcript        ENST00000428480.1
13   ENSG00000244137 Transcript        ENST00000452640.1
14   ENSG00000135773 Transcript        ENST00000480004.1
15   -               RegulatoryFeature ENSR00000317877
16   -               MotifFeature      ENSM00527917318
17   -               -                 -
18   ENSG00000171067 Transcript        ENST00000304271.6
19   ENSG00000171067 Transcript        ENST00000530166.1
20   ENSG00000171067 Transcript        ENST00000531745.1
21   ENSG00000171067 Transcript        ENST00000533310.1
22   ENSG00000163932 Transcript        ENST00000330452.3
23   ENSG00000163932 Transcript        ENST00000394729.2
24   ENSG00000273482 Transcript        ENST00000608339.1
25   ENSG00000273482 Transcript        ENST00000608438.1
26   ENSG00000112041 Transcript        ENST00000229771.6
27   ENSG00000112041 Transcript        ENST00000322263.4
28   ENSG00000007866 Transcript        ENST00000338863.7
29   ENSG00000112041 Transcript        ENST00000373892.4
30   ENSG00000007866 Transcript        ENST00000402886.3
...  ...             ...               ...
2271 ENSG00000272687 Transcript        ENST00000609496.1
2272 ENSG00000272687 Transcript        ENST00000609624.1
2273 ENSG00000272687 Transcript        ENST00000609624.1
2274 ENSG00000272687 Transcript        ENST00000610176.1
2275 ENSG00000272687 Transcript        ENST00000610176.1
2276 ENSG00000272687 Transcript        ENST00000608285.1
2277 ENSG00000272687 Transcript        ENST00000608285.1
2278 ENSG00000272687 Transcript        ENST00000608285.1
2279 ENSG00000272687 Transcript        ENST00000608398.1
2280 ENSG00000272687 Transcript        ENST00000608398.1
2281 ENSG00000272687 Transcript        ENST00000608398.1
2282 ENSG00000272687 Transcript        ENST00000608828.1
2283 ENSG00000272687 Transcript        ENST00000608828.1
2284 ENSG00000272687 Transcript        ENST00000608828.1
2285 ENSG00000272687 Transcript        ENST00000609357.1
2286 ENSG00000272687 Transcript        ENST00000609357.1
2287 ENSG00000272687 Transcript        ENST00000609357.1
2288 ENSG00000272687 Transcript        ENST00000609397.1
2289 ENSG00000272687 Transcript        ENST00000609397.1
2290 ENSG00000272687 Transcript        ENST00000609397.1
2291 ENSG00000272687 Transcript        ENST00000609496.1
2292 ENSG00000272687 Transcript        ENST00000609496.1
2293 ENSG00000272687 Transcript        ENST00000609496.1
2294 ENSG00000272687 Transcript        ENST00000609624.1
2295 ENSG00000272687 Transcript        ENST00000609624.1
2296 ENSG00000272687 Transcript        ENST00000609624.1
2297 ENSG00000272687 Transcript        ENST00000610176.1
2298 ENSG00000272687 Transcript        ENST00000610176.1
2299 ENSG00000272687 Transcript        ENST00000610176.1
2300 -               -                 -
     biotype                 ...
1    protein_coding          ...
2    protein_coding          ...
3    protein_coding          ...
4    antisense               ...
5    antisense               ...
6    antisense               ...
7    processed_transcript    ...
8    protein_coding          ...
9    protein_coding          ...
10   protein_coding          ...
11   antisense               ...
12   antisense               ...
13   antisense               ...
14   processed_transcript    ...
15   CTCF_binding_site       ...
16   -                       ...
17   -                       ...
18   protein_coding          ...
19   processed_transcript    ...
20   processed_transcript    ...
21   protein_coding          ...
22   protein_coding          ...
23   protein_coding          ...
24   protein_coding          ...
25   protein_coding          ...
26   protein_coding          ...
27   protein_coding          ...
28   protein_coding          ...
29   retained_intron         ...
30   protein_coding          ...
...  ...
2271 protein_coding          ...
2272 nonsense_mediated_decay ...
2273 nonsense_mediated_decay ...
2274 nonsense_mediated_decay ...
2275 nonsense_mediated_decay ...
2276 nonsense_mediated_decay ...
2277 nonsense_mediated_decay ...
2278 nonsense_mediated_decay ...
2279 protein_coding          ...
2280 protein_coding          ...
2281 protein_coding          ...
2282 protein_coding          ...
2283 protein_coding          ...
2284 protein_coding          ...
2285 protein_coding          ...
2286 protein_coding          ...
2287 protein_coding          ...
2288 retained_intron         ...
2289 retained_intron         ...
2290 retained_intron         ...
2291 protein_coding          ...
2292 protein_coding          ...
2293 protein_coding          ...
2294 nonsense_mediated_decay ...
2295 nonsense_mediated_decay ...
2296 nonsense_mediated_decay ...
2297 nonsense_mediated_decay ...
2298 nonsense_mediated_decay ...
2299 nonsense_mediated_decay ...
2300 -                       ...
     PHENOTYPES
1    -
2    -
3    -
4    -
5    -
6    -
7    -
8    -
9    -
10   -
11   -
12   -
13   -
14   -
15   -
16   -
17   -
18   -
19   -
20   -
21   -
22   -
23   -
24   -
25   -
26   LEBER_CONGENITAL_AMAUROSIS_15+MIM_morbid+ENSG00000112041,RETINITIS_PIGMENTOSA_14+MIM_morbid+ENSG00000112041,Leber_congenital_amaurosis+Orphanet+ENSG00000112041,Retinitis_pigmentosa+Orphanet+ENSG00000112041
27   LEBER_CONGENITAL_AMAUROSIS_15+MIM_morbid+ENSG00000112041,RETINITIS_PIGMENTOSA_14+MIM_morbid+ENSG00000112041,Leber_congenital_amaurosis+Orphanet+ENSG00000112041,Retinitis_pigmentosa+Orphanet+ENSG00000112041
28   LEBER_CONGENITAL_AMAUROSIS_15+MIM_morbid+ENSG00000112041,RETINITIS_PIGMENTOSA_14+MIM_morbid+ENSG00000112041,Leber_congenital_amaurosis+Orphanet+ENSG00000112041,Retinitis_pigmentosa+Orphanet+ENSG00000112041
29   LEBER_CONGENITAL_AMAUROSIS_15+MIM_morbid+ENSG00000112041,RETINITIS_PIGMENTOSA_14+MIM_morbid+ENSG00000112041,Leber_congenital_amaurosis+Orphanet+ENSG00000112041,Retinitis_pigmentosa+Orphanet+ENSG00000112041
30   LEBER_CONGENITAL_AMAUROSIS_15+MIM_morbid+ENSG00000112041,RETINITIS_PIGMENTOSA_14+MIM_morbid+ENSG00000112041,Leber_congenital_amaurosis+Orphanet+ENSG00000112041,Retinitis_pigmentosa+Orphanet+ENSG00000112041
...  ...
2271 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718
2272 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718
2273 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718
2274 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718
2275 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718,QRS_duration+NHGRI-EBI_GWAS_catalog+rs4687718
2276 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2277 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2278 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2279 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2280 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2281 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2282 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2283 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2284 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2285 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2286 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2287 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2288 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2289 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2290 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2291 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2292 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2293 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2294 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2295 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2296 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2297 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2298 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2299 Short_Stature__Developmental_Delay__and_Congenital_Heart_Defects+DDG2P+ENSG00000272687
2300 -
     Mastermind_MMID3
1    CAPN9:R459W,CAPN9:R496W,CAPN9:R522W
2    CAPN9:R459W,CAPN9:R496W,CAPN9:R522W
3    CAPN9:R459W,CAPN9:R496W,CAPN9:R522W
4    -
5    -
6    -
7    -
8    CAPN9:E470int,CAPN9:E470inta,CAPN9:E507int,CAPN9:E507inta,CAPN9:E533int,CAPN9:E533inta
9    CAPN9:E470int,CAPN9:E470inta,CAPN9:E507int,CAPN9:E507inta,CAPN9:E533int,CAPN9:E533inta
10   CAPN9:E470int,CAPN9:E470inta,CAPN9:E507int,CAPN9:E507inta,CAPN9:E533int,CAPN9:E533inta
11   CAPN9:E470int,CAPN9:E470inta,CAPN9:E507int,CAPN9:E507inta,CAPN9:E533int,CAPN9:E533inta
12   CAPN9:E470int,CAPN9:E470inta,CAPN9:E507int,CAPN9:E507inta,CAPN9:E533int,CAPN9:E533inta
13   CAPN9:E470int,CAPN9:E470inta,CAPN9:E507int,CAPN9:E507inta,CAPN9:E533int,CAPN9:E533inta
14   -
15   -
16   -
17   -
18   -
19   -
20   -
21   -
22   -
23   -
24   -
25   -
26   -
27   -
28   -
29   -
30   -
...  ...
2271 -
2272 -
2273 -
2274 -
2275 -
2276 -
2277 -
2278 -
2279 -
2280 -
2281 -
2282 -
2283 -
2284 -
2285 -
2286 -
2287 -
2288 -
2289 -
2290 -
2291 -
2292 -
2293 -
2294 -
2295 -
2296 -
2297 -
2298 -
2299 -
2300 -
     Geno2MP_HPO_count Geno2MP_URL CADD_phred CADD_RAW  OR     P     gene
1    -                 -           22.1       2.314699  2.6060 0.000 NA
2    -                 -           22.1       2.314699  2.6060 0.000 NA
3    -                 -           22.1       2.314699  2.6060 0.000 NA
4    -                 -           22.1       2.314699  2.6060 0.000 NA
5    -                 -           22.1       2.314699  2.6060 0.000 NA
6    -                 -           22.1       2.314699  2.6060 0.000 NA
7    -                 -           22.1       2.314699  2.6060 0.000 NA
8    -                 -           0.271      -0.343595 2.1740 0.000 agt
9    -                 -           0.271      -0.343595 2.1740 0.000 agt
10   -                 -           0.271      -0.343595 2.1740 0.000 agt
11   -                 -           0.271      -0.343595 2.1740 0.000 agt
12   -                 -           0.271      -0.343595 2.1740 0.000 agt
13   -                 -           0.271      -0.343595 2.1740 0.000 agt
14   -                 -           0.271      -0.343595 2.1740 0.000 agt
15   -                 -           0.257      -0.351055 1.9340 0.001 csnk1a1
16   -                 -           0.257      -0.351055 1.9340 0.001 csnk1a1
17   -                 -           0.257      -0.351055 1.9340 0.001 csnk1a1
18   -                 -           6.006      0.211244  0.4482 0.003 lrp5
19   -                 -           6.006      0.211244  0.4482 0.003 lrp5
20   -                 -           6.006      0.211244  0.4482 0.003 lrp5
21   -                 -           6.006      0.211244  0.4482 0.003 lrp5
22   -                 -           6.551      0.249872  1.8150 0.005 NA

In [131]:
combined <- inner_join(combined, rank)

Joining with `by = join_by(marker)`

In [142]:
setdiff(rank$marker, combined$marker)

character(0)

In [143]:
xslx_format <- function(df, col) {
    df[[col]] <- as.character(df[[col]])
    df[[col]] <- gsub(",", ";", df[[col]])
    df[[col]]<- gsub("/","of", df[[col]])
    return(df)
}

In [144]:
xslx_format <- function(col) {
  col <- gsub(",", ";", col)
  col <- gsub("/", "of", col)
  return(col)
}

In [150]:
withUnpruned <- withUnpruned %>% 
    mutate(across(where(is.character), xslx_format)) %>% 
      distinct()

In [67]:
combined <- combined %>%
  mutate(across(where(is.character), xslx_format)) %>% 
  distinct()

In [69]:
write.csv(combined , "./result/pruned_vep.csv", quote=FALSE, row.names=FALSE)

In [152]:
write.csv(withUnpruned, "./result/nonpruned_vep.csv")

In [233]:
GTEX <- combined %>% 
distinct(marker, allele, xgboost_score) %>% 
arrange(desc(xgboost_score))
GTEX

   marker      allele xgboost_score
1  rs6887452   G      100.00000
2  rs56022120  T       75.66017
3  rs9658119   C       73.18871
4  rs17879591  T       69.74603
5  rs12462974  C       64.67756
6  rs79722771  T       64.26292
7  rs6799185   T       60.02445
8  rs12082061  T       51.47215
9  rs11228184  A       50.88202
10 rs62378010  C       44.27093
11 rs3730179   A       41.24731
12 rs2454104   A       39.81110
13 rs3803919   G       38.88170
14 rs2306862   T       36.21323
15 rs3789647   T       33.40229
16 rs474742    A       30.64549
17 rs999813    T       29.66423
18 rs61828616  T       26.52289
19 rs353294    C       23.32032
20 rs3790960   A       21.11465
21 rs1887490   G       19.90525
22 rs113800014 T       18.90261
23 rs10476909  C       18.64690
24 rs10864772  T       18.64652
25 rs12417014  T       18.19817
26 rs2067853   A       16.34108
27 rs11826287  C       16.33313
28 rs76626846  A       15.04861
29 rs6687027   A       14.59705
30 rs2297831   T       14.28059
31 rs872505    T       11.87941
32 rs7936582   C        8.41272

In [234]:
write.csv(GTEX , "./result/gtex.csv", quote=FALSE, row.names=FALSE)