In [1]:
import requests, sys, json
import pandas as pd
import pymongo
import numpy as np

In [2]:
# Retrieve VEP objects 
def lookup_variant_effects(id_list):
 
    server = "https://grch37.rest.ensembl.org"
    ext = "/vep/human/id?canonical=1;CADD=1;vcf_string=1;SIFT=1;PolyPhen=1;domains=1;DisGeNET=1;EVE=1;GO=1;Mastermind=1;Phenotypes=1;mutfunc=1;variant_class=1;xref_refseq=1"
    
    headers={ "Content-Type" : "application/json", "Accept" : "application/json"}
    
    # Define the request body as a JSON string with the list of variant IDs
    data = {"ids": id_list}
    json_data = json.dumps(data) # the data will be in this format with the single quotations: '{"ids" : ["rs56116432", "COSM476" ] }'
    # Additional parameters for the VEP API


    r = requests.post(server+ext, headers=headers, data=json_data)

    if not r.ok:
      r.raise_for_status()
      sys.exit()

    decoded = r.json()
    
    return decoded
# print(type(repr(decoded)))

In [3]:
# load data
new = []

with open ("rsid_six_gene.txt", "r") as f:
    #entire content
    lines = f.readlines()

variant_ids = [line.strip() for line in lines]
len(variant_ids)

302

In [4]:
a = lookup_variant_effects(variant_ids[0:150])

In [5]:
b = lookup_variant_effects(variant_ids[151:302])

In [6]:
variant_effect = a + b 
df = pd.DataFrame(variant_effect )

In [7]:
df

,vcf_string,seq_region_name,input,most_severe_consequence,end,start,assembly_name,colocated_variants,allele_string,regulatory_feature_consequences,id,strand,transcript_consequences,variant_class,intergenic_consequences,motif_feature_consequences
0,5-148802811-A-C,5,rs353294,non_coding_transcript_exon_variant,148802811,148802811,GRCh37,"[{'end': 148802811, 'start': 148802811, 'stran...",A/C,"[{'variant_allele': 'C', 'cadd_phred': 3.093, ...",rs353294,1,"[{'gene_id': 'ENSG00000249669', 'biotype': 'li...",SNV,NaN,NaN
1,5-149001897-A-G,5,rs77489920,intron_variant,149001897,149001897,GRCh37,"[{'start': 149001897, 'end': 149001897, 'stran...",A/G,NaN,rs77489920,1,"[{'canonical': 1, 'cadd_phred': 6.479, 'varian...",SNV,NaN,NaN
2,5-149012782-G-A,5,rs3733658,3_prime_UTR_variant,149012782,149012782,GRCh37,"[{'minor_allele_freq': 0.2644, 'allele_string'...",G/A,"[{'cadd_raw': -0.044382, 'regulatory_feature_i...",rs3733658,1,"[{'cdna_end': 3219, 'cdna_start': 3219, 'gene_...",SNV,NaN,NaN
3,5-148981046-T-C,5,rs1379544,intron_variant,148981046,148981046,GRCh37,"[{'seq_region_name': '5', 'frequencies': {'C':...",T/C,NaN,rs1379544,1,"[{'consequence_terms': ['intron_variant'], 'hg...",SNV,NaN,NaN
4,5-148825669-C-T,5,rs10062536,intergenic_variant,148825669,148825669,GRCh37,"[{'seq_region_name': '5', 'minor_allele': 'T',...",C/T,NaN,rs10062536,1,NaN,SNV,"[{'variant_allele': 'T', 'cadd_raw': 0.34148, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,"[3-53282303-A-G, 3-53282303-A-T]",3,rs4687718,intron_variant,53282303,53282303,GRCh37,"[{'start': 53282303, 'allele_string': 'A/G/T',...",A/G/T,NaN,rs4687718,1,"[{'mastermind_counts': '35|35|79', 'consequenc...",SNV,NaN,NaN
319,"[HG957_PATCH-53282303-A-G, HG957_PATCH-5328230...",HG957_PATCH,rs4687718,intron_variant,53282303,53282303,GRCh37,"[{'end': 53282303, 'id': 'rs4687718', 'minor_a...",A/G/T,NaN,rs4687718,1,"[{'transcript_id': 'ENST00000608285', 'strand'...",SNV,NaN,NaN
320,3-53125585-T-C,3,rs2564921,3_prime_UTR_variant,53125585,53125585,GRCh37,"[{'var_synonyms': {'ClinVar': ['RCV000365605',...",T/C,NaN,rs2564921,1,"[{'canonical': 1, 'cadd_phred': 0.294, 'transc...",SNV,NaN,NaN
321,3-53140603-T-C,3,rs1004807,intron_variant,53140603,53140603,GRCh37,"[{'frequencies': {'C': {'eas': 0.8542, 'afr': ...",T/C,NaN,rs1004807,1,"[{'strand': -1, 'gene_symbol': 'RFT1', 'master...",SNV,NaN,NaN
322,3-53101580-C-T,3,rs6799185,intron_variant,53101580,53101580,GRCh37,"[{'minor_allele': 'T', 'id': 'rs6799185', 'end...",C/T,NaN,rs6799185,1,"[{'biotype': 'processed_pseudogene', 'gene_sym...",SNV,NaN,NaN

* 278 SNPs in exon regions
* 45 SNPs in intronic regions
* 112 SNPs involved in regulatory

In [31]:
323 - df["intergenic_consequences"].isna().sum()

45

In [32]:
323 - df["transcript_consequences"].isna().sum()

278

In [33]:
323- df["regulatory_feature_consequences"].isna().sum()

112

## The 6 Driving Genes
* PRKCD: ENSG00000163932 : 5580
* LRP5: ENSG00000162337 : 4041
* PPARD: ENSG00000112033 : 5467
* CSNK1A1: ENSG00000113712 : 1452
* AGT : ENSG00000135744 : 183
* PIK3R2 : ENSG00000105647 : 5296

In [7]:
### Capture Variants of all types of variants of these genes
name = ["ENSG00000163932", "ENSG00000162337", "ENSG00000112033", "ENSG00000113712", "ENSG00000135744","ENSG00000105647"]
for i in range(0,len(variant_effect)):
    list_intron = []
list_exon = []
name = ["ENSG00000163932", "ENSG00000162337", "ENSG00000112033", "ENSG00000113712", "ENSG00000135744","ENSG00000105647"]
for i in range(0,len(variant_effect)):
    if "intergenic_consequences" in variant_effect[i].keys():
        list_intron.append((df["id"][i],variant_effect[i]["intergenic_consequences"][0]))
        
    elif "transcript_consequences" in variant_effect[i].keys():
        for dic in variant_effect[i]["transcript_consequences"]:
            if dic["gene_id"] in name:
                list_exon.append((df["id"][i],dic))

complete_list_all = list_intron + list_exon  
len(complete_list_all)

519

In [8]:
complete_list_all

[('rs10062536',
  {'impact': 'MODIFIER',
   'cadd_phred': 7.734,
   'cadd_raw': 0.34148,
   'variant_allele': 'T',
   'consequence_terms': ['intergenic_variant']}),
 ('rs414582',
  {'impact': 'MODIFIER',
   'cadd_raw': -0.30287,
   'cadd_phred': 0.359,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'C'}),
 ('rs10061434',
  {'impact': 'MODIFIER',
   'cadd_raw': -0.059472,
   'cadd_phred': 1.828,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'T'}),
 ('rs10454990',
  {'impact': 'MODIFIER',
   'cadd_raw': 0.083336,
   'cadd_phred': 3.983,
   'phenotypes': [{'p_value': 5e-06,
     'end': 148838117,
     'odds_ratio': 4.558,
     'start': 148838117,
     'type': 'Variation',
     'strand': '+',
     'seq_region_name': '5',
     'source': 'NHGRI-EBI_GWAS_catalog',
     'id': 'rs10454990',
     'associated_gene': 'MIR143HG,CSNK1A1',
     'variation_names': 'rs10454990',
     'risk_allele': 'C',
     'phenotype': 'Carotid intima media thickness x smoking interaction'}],
   'variant_allele': 'G',
   'consequence_terms': ['intergenic_variant']}),
 ('rs72823546',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'impact': 'MODIFIER',
   'cadd_raw': 0.228896,
   'cadd_phred': 6.259}),
 ('rs353237',
  {'variant_allele': 'G',
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': 0.459367,
   'cadd_phred': 9.011}),
 ('rs4705346',
  {'impact': 'MODIFIER',
   'cadd_phred': 7.554,
   'cadd_raw': 0.326805,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A'}),
 ('rs11745684',
  {'cadd_raw': -0.069812,
   'cadd_phred': 1.712,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'T'}),
 ('rs2454104',
  {'impact': 'MODIFIER',
   'cadd_phred': 0.257,
   'cadd_raw': -0.351055,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A'}),
 ('rs78578633',
  {'cadd_phred': 9.385,
   'cadd_raw': 0.498089,
   'impact': 'MODIFIER',
   'variant_allele': 'T',
   'consequence_terms': ['intergenic_variant']}),
 ('rs17724303',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_phred': 1.64,
   'cadd_raw': -0.076466,
   'impact': 'MODIFIER'}),
 ('rs447950',
  {'cadd_phred': 11.29,
   'cadd_raw': 0.717338,
   'impact': 'MODIFIER',
   'variant_allele': 'A',
   'consequence_terms': ['intergenic_variant']}),
 ('rs72823547',
  {'impact': 'MODIFIER',
   'cadd_raw': 0.193563,
   'cadd_phred': 5.744,
   'variant_allele': 'T',
   'consequence_terms': ['intergenic_variant']}),
 ('rs73279543',
  {'variant_allele': 'G',
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': -0.162437,
   'cadd_phred': 0.924}),
 ('rs452366',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'impact': 'MODIFIER',
   'cadd_phred': 1.069,
   'cadd_raw': -0.140876}),
 ('rs241280',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'T',
   'impact': 'MODIFIER',
   'cadd_raw': -0.460428,
   'cadd_phred': 0.118}),
 ('rs353248',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'impact': 'MODIFIER',
   'cadd_raw': -0.384941,
   'cadd_phred': 0.202}),
 ('rs353243',
  {'variant_allele': 'A',
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_phred': 5.374,
   'cadd_raw': 0.169239}),
 ('rs353241',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_raw': -0.141188,
   'cadd_phred': 1.067,
   'impact': 'MODIFIER'}),
 ('rs62378023',
  {'impact': 'MODIFIER',
   'cadd_phred': 4.452,
   'cadd_raw': 0.111457,
   'variant_allele': 'T',
   'consequence_terms': ['intergenic_variant']}),
 ('rs118050745',
  {'variant_allele': 'C',
   'consequence_terms': ['intergenic_variant'],
   'cadd_raw': -0.174227,
   'cadd_phred': 0.853,
   'impact': 'MODIFIER'}),
 ('rs113800014',
  {'variant_allele': 'T',
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': -0.186207,
   'cadd_phred': 0.788}),
 ('rs11602367',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'C',
   'impact': 'MODIFIER',
   'cadd_raw': -0.050675,
   'cadd_phred': 1.932}),
 ('rs474742',
  {'variant_allele': 'A',
   'consequence_terms': ['intergenic_variant'],
   'cadd_phred': 3.44,
   'cadd_raw': 0.050944,
   'impact': 'MODIFIER'}),
 ('rs4713858',
  {'variant_allele': 'G',
   'consequence_terms': ['intergenic_variant'],
   'phenotypes': [{'end': 35402785,
     'p_value': 4e-08,
     'type': 'Variation',
     'strand': '+',
     'seq_region_name': '6',
     'source': 'NHGRI-EBI_GWAS_catalog',
     'id': 'rs4713858',
     'odds_ratio': 6.8,
     'start': 35402785,
     'associated_gene': 'ANKS1A,TCP11,ZNF76,DEF6,SCUBE3',
     'variation_names': 'rs4713858',
     'risk_allele': 'G',
     'phenotype': 'Height'}],
   'cadd_raw': -0.039583,
   'cadd_phred': 2.07,
   'impact': 'MODIFIER'}),
 ('rs6457821',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'phenotypes': [{'p_value': 1.823e-11,
     'risk_allele': 'C',
     'phenotype': 'Height',
     'end': 35402805,
     'start': 35402805,
     'id': 'rs6457821',
     'source': 'GIANT',
     'seq_region_name': '6',
     'strand': '+',
     'type': 'Variation'},
    {'variation_names': 'rs6457821',
     'phenotype': 'Height',
     'risk_allele': 'A',
     'associated_gene': 'PPARD/FANCE',
     'beta_coef': '0.104 unit decrease',
     'seq_region_name': '6',
     'source': 'NHGRI-EBI_GWAS_catalog',
     'id': 'rs6457821',
     'type': 'Variation',
     'strand': '+',
     'start': 35402805,
     'end': 35402805,
     'p_value': 2e-12}],
   'cadd_raw': 0.044029,
   'cadd_phred': 3.325,
   'impact': 'MODIFIER'}),
 ('rs115269427',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_phred': 1.099,
   'cadd_raw': -0.136784,
   'impact': 'MODIFIER'}),
 ('rs78945013',
  {'impact': 'MODIFIER',
   'cadd_phred': 1.633,
   'cadd_raw': -0.077146,
   'variant_allele': 'T',
   'consequence_terms': ['intergenic_variant']}),
 ('rs853469',
  {'impact': 'MODIFIER',
   'variant_allele': 'C',
   'consequence_terms': ['intergenic_variant'],
   'cadd_phred': 2.187,
   'cadd_raw': -0.03063,
   'phenotypes': [{'p_value': 5.491e-05,
     'seq_region_name': '1',
     'end': 230759310,
     'strand': '+',
     'start': 230759310,
     'type': 'Variation',
     'source': 'dbGaP',
     'associated_gene': 'RPS24P4,COG2',
     'phenotype': 'Body Mass Index',
     'variation_names': 'rs853469',
     'id': 'rs853469'}]}),
 ('rs12031571',
  {'cadd_raw': -0.019374,
   'cadd_phred': 2.342,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'impact': 'MODIFIER'}),
 ('rs77645389',
  {'cadd_phred': 1.201,
   'cadd_raw': -0.123666,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'T',
   'impact': 'MODIFIER'}),
 ('rs4846997',
  {'impact': 'MODIFIER',
   'variant_allele': 'A',
   'cadd_raw': -0.117906,
   'cadd_phred': 1.248,
   'consequence_terms': ['intergenic_variant']}),
 ('rs11122563',
  {'impact': 'MODIFIER',
   'variant_allele': 'C',
   'consequence_terms': ['intergenic_variant'],
   'cadd_phred': 3.128,
   'cadd_raw': 0.032074}),
 ('rs11122562',
  {'consequence_terms': ['intergenic_variant'],
   'cadd_raw': -0.11617,
   'cadd_phred': 1.263,
   'variant_allele': 'A',
   'impact': 'MODIFIER'}),
 ('rs62120362',
  {'impact': 'MODIFIER',
   'variant_allele': 'C',
   'consequence_terms': ['intergenic_variant'],
   'cadd_phred': 1.901,
   'cadd_raw': -0.053287}),
 ('rs115659375',
  {'impact': 'MODIFIER',
   'variant_allele': 'A',
   'cadd_raw': -0.318184,
   'cadd_phred': 0.323,
   'consequence_terms': ['intergenic_variant']}),
 ('rs115659375',
  {'impact': 'MODIFIER',
   'variant_allele': 'A',
   'consequence_terms': ['intergenic_variant']}),
 ('rs11919522',
  {'variant_allele': 'C',
   'impact': 'MODIFIER',
   'cadd_phred': 3.361,
   'cadd_raw': 0.046178,
   'consequence_terms': ['intergenic_variant']}),
 ('rs11919522',
  {'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'C',
   'impact': 'MODIFIER'}),
 ('rs115657945',
  {'consequence_terms': ['intergenic_variant'],
   'cadd_raw': 0.393143,
   'cadd_phred': 8.324,
   'variant_allele': 'T',
   'impact': 'MODIFIER'}),
 ('rs79843306',
  {'variant_allele': 'A',
   'impact': 'MODIFIER',
   'cadd_raw': -0.326153,
   'cadd_phred': 0.305,
   'consequence_terms': ['intergenic_variant']}),
 ('rs79843306',
  {'impact': 'MODIFIER',
   'variant_allele': 'A',
   'consequence_terms': ['intergenic_variant']}),
 ('rs116071986',
  {'variant_allele': 'A',
   'impact': 'MODIFIER',
   'cadd_phred': 5.038,
   'cadd_raw': 0.147698,
   'consequence_terms': ['intergenic_variant']}),
 ('rs7610701',
  {'cadd_phred': 4.537,
   'cadd_raw': 0.116617,
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'impact': 'MODIFIER'}),
 ('rs1080500',
  {'phenotypes': [{'phenotype': 'Autism spectrum disorder or schizophrenia',
     'associated_gene': 'GLT8D1,GNL3,ITIH1,ITIH3,ITIH4,ITIH4-AS1,MIR8064,MUSTN1,NEK4,NT5DC2,PBRM1,RFT1,SFMBT1,SMIM4,SNORD136,SNORD19,SNORD19B,SNORD69,SPCS1,STAB1,TMEM110,TMEM110-MUSTN1',
     'variation_names': 'rs1080500',
     'id': 'rs1080500',
     'type': 'Variation',
     'source': 'NHGRI-EBI_GWAS_catalog',
     'end': 53175017,
     'start': 53175017,
     'strand': '+',
     'odds_ratio': 1.0638298,
     'p_value': 6e-09,
     'seq_region_name': '3'}],
   'impact': 'MODIFIER',
   'variant_allele': 'A',
   'cadd_raw': 0.853995,
   'cadd_phred': 12.37,
   'consequence_terms': ['intergenic_variant']}),
 ('rs2125130',
  {'gene_symbol': 'CSNK1A1',
   'go': 'GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0004713:protein_tyrosine_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'transcript_id': 'ENST00000261798',
   'hgnc_id': 2451,
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'variant_allele': 'A',
   'consequence_terms': ['intron_variant'],
   'biotype': 'protein_coding',
   'gene_id': 'ENSG00000113712',
   'strand': -1,
   'cadd_phred': 0.469,
   'cadd_raw': -0.26352}),
 ('rs2125130',
  {'gene_symbol': 'CSNK1A1',
   'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0004713:protein_tyrosine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'transcript_id': 'ENST00000377843',
   'hgnc_id': 2451,
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'consequence_terms': ['intron_variant'],
   'variant_allele': 'A',
   'cadd_raw': -0.26352,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 0.469,
   'strand': -1,
   'biotype': 'protein_coding',
   'refseq_transcript_ids': ['NM_001271741.1',
    'NM_001892.5',
    'NM_001025105.2']}),
 ('rs2125130',
  {'cadd_raw': -0.26352,
   'flags': ['cds_start_NF'],
   'consequence_terms': ['upstream_gene_variant'],
   'variant_allele': 'A',
   'hgnc_id': 2451,
   'impact': 'MODIFIER',
   'strand': -1,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 0.469,
   'biotype': 'protein_coding',
   'distance': 465,
   'transcript_id': 'ENST00000503350',
   'gene_symbol_source': 'HGNC',
   'gene_symbol': 'CSNK1A1',
   'go': 'GO:0004672:protein_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups'}),
 ('rs2125130',
  {'consequence_terms': ['intron_variant'],
   'variant_allele': 'A',
   'cadd_phred': 0.469,
   'gene_id': 'ENSG00000113712',
   'cadd_raw': -0.26352,
   'strand': -1,
   'biotype': 'protein_coding',
   'gene_symbol': 'CSNK1A1',
   'go': 'GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'transcript_id': 'ENST00000504676',
   'hgnc_id': 2451,
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC'}),
 ('rs2125130',
  {'consequence_terms': ['intron_variant'],
   'variant_allele': 'A',
   'refseq_transcript_ids': ['NM_001271742.1'],
   'gene_id': 'ENSG00000113712',
   'strand': -1,
   'cadd_phred': 0.469,
   'cadd_raw': -0.26352,
   'biotype': 'protein_coding',
   'go': 'GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'gene_symbol': 'CSNK1A1',
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'transcript_id': 'ENST00000515435',
   'hgnc_id': 2451}),
 ('rs2125130',
  {'consequence_terms': ['intron_variant'],
   'variant_allele': 'A',
   'gene_id': 'ENSG00000113712',
   'cadd_raw': -0.26352,
   'cadd_phred': 0.469,
   'strand': -1,
   'biotype': 'protein_coding',
   'canonical': 1,
   'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'gene_symbol': 'CSNK1A1',
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'transcript_id': 'ENST00000515768',
   'hgnc_id': 2451}),
 ('rs2125130',
  {'strand': -1,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 0.469,
   'cadd_raw': -0.26352,
   'biotype': 'protein_coding',
   'distance': 410,
   'consequence_terms': ['upstream_gene_variant'],
   'variant_allele': 'A',
   'transcript_id': 'ENST00000606299',
   'hgnc_id': 2451,
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'gene_symbol': 'CSNK1A1',
   'go': 'GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups'}),
 ('rs2125130',
  {'biotype': 'protein_coding',
   'distance': 401,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 0.469,
   'strand': -1,
   'cadd_raw': -0.26352,
   'variant_allele': 'A',
   'consequence_terms': ['upstream_gene_variant'],
   'gene_symbol_source': 'HGNC',
   'impact': 'MODIFIER',
   'hgnc_id': 2451,
   'transcript_id': 'ENST00000606719',
   'go': 'GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'gene_symbol': 'CSNK1A1'}),
 ('rs2125130',
  {'impact': 'MODIFIER',
   'hgnc_id': 2451,
   'flags': ['cds_start_NF'],
   'cadd_raw': -0.26352,
   'variant_allele': 'A',
   'consequence_terms': ['upstream_gene_variant'],
   'gene_symbol_source': 'HGNC',
   'transcript_id': 'ENST00000606826',
   'go': 'GO:0004672:protein_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'gene_symbol': 'CSNK1A1',
   'biotype': 'nonsense_mediated_decay',
   'distance': 502,
   'gene_id': 'ENSG00000113712',
   'strand': -1,
   'cadd_phred': 0.469}),
 ('rs111416523',
  {'variant_allele': 'C',
   'consequence_terms': ['intron_variant'],
   'biotype': 'protein_coding',
   'gene_id': 'ENSG00000113712',
   'cadd_raw': -0.06643,
   'cadd_phred': 1.749,
   'strand': -1,
   'gene_symbol': 'CSNK1A1',
   'go': 'GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0004713:protein_tyrosine_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'hgnc_id': 2451,
   'transcript_id': 'ENST00000261798',
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC'}),
 ('rs111416523',
  {'transcript_id': 'ENST00000377843',
   'hgnc_id': 2451,
   'gene_symbol_source': 'HGNC',
   'impact': 'MODIFIER',
   'gene_symbol': 'CSNK1A1',
   'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0004713:protein_tyrosine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'biotype': 'protein_coding',
   'gene_id': 'ENSG00000113712',
   'strand': -1,
   'cadd_phred': 1.749,
   'cadd_raw': -0.06643,
   'refseq_transcript_ids': ['NM_001271741.1',
    'NM_001892.5',
    'NM_001025105.2'],
   'variant_allele': 'C',
   'consequence_terms': ['intron_variant']}),
 ('rs111416523',
  {'variant_allele': 'C',
   'consequence_terms': ['intron_variant'],
   'biotype': 'protein_coding',
   'strand': -1,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 1.749,
   'cadd_raw': -0.06643,
   'go': 'GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'gene_symbol': 'CSNK1A1',
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'transcript_id': 'ENST00000504676',
   'hgnc_id': 2451}),
 ('rs111416523',
  {'biotype': 'protein_coding',
   'strand': -1,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 1.749,
   'cadd_raw': -0.06643,
   'refseq_transcript_ids': ['NM_001271742.1'],
   'variant_allele': 'C',
   'consequence_terms': ['intron_variant'],
   'transcript_id': 'ENST00000515435',
   'hgnc_id': 2451,
   'gene_symbol_source': 'HGNC',
   'impact': 'MODIFIER',
   'gene_symbol': 'CSNK1A1',
   'go': 'GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005524:ATP_binding,GO:0006468:protein_phosphorylation,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups'}),
 ('rs111416523',
  {'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'canonical': 1,
   'gene_symbol': 'CSNK1A1',
   'impact': 'MODIFIER',
   'gene_symbol_source': 'HGNC',
   'transcript_id': 'ENST00000515768',
   'hgnc_id': 2451,
   'variant_allele': 'C',
   'consequence_terms': ['intron_variant'],
   'biotype': 'protein_coding',
   'strand': -1,
   'gene_id': 'ENSG00000113712',
   'cadd_phred': 1.749,
   'cadd_raw': -0.06643}),
 ('rs111416523',
  {'gene_id': 'ENSG00000113712',
   'cadd_phred': 1.749,
   'cadd_raw': -0.06643,
   'strand': -1,
   'biotype': 'nonsense_mediated_decay',
   'distance': 4144,
   'consequence_terms': ['downstream_gene_variant'],
   'variant_allele': 'C',
   'transcript_id': 'ENST00000523203',
   'hgnc_id': 2451,

In [9]:
df_2_all = pd.DataFrame(complete_list_all, columns = ["id","consequences"])
expanded_df = df_2_all["consequences"].apply(pd.Series)
df_2_all = pd.concat([df_2_all, expanded_df], axis=1)

In [10]:
df_2_all

,id,consequences,impact,cadd_phred,cadd_raw,variant_allele,consequence_terms,phenotypes,gene_symbol,go,...,domains,cdna_start,protein_end,protein_start,sift_prediction,cdna_end,cds_start,codons,polyphen_prediction,sift_score
0,rs10062536,"{'impact': 'MODIFIER', 'cadd_phred': 7.734, 'c...",MODIFIER,7.734,0.341480,T,[intergenic_variant],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,rs414582,"{'impact': 'MODIFIER', 'cadd_raw': -0.30287, '...",MODIFIER,0.359,-0.302870,C,[intergenic_variant],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,rs10061434,"{'impact': 'MODIFIER', 'cadd_raw': -0.059472, ...",MODIFIER,1.828,-0.059472,T,[intergenic_variant],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,rs10454990,"{'impact': 'MODIFIER', 'cadd_raw': 0.083336, '...",MODIFIER,3.983,0.083336,G,[intergenic_variant],"[{'p_value': 5e-06, 'end': 148838117, 'odds_ra...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,rs72823546,"{'consequence_terms': ['intergenic_variant'], ...",MODIFIER,6.259,0.228896,A,[intergenic_variant],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,rs1483185,"{'cadd_raw': 0.154256, 'strand': 1, 'gene_symb...",MODIFIER,5.142,0.154256,G,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004699:calc...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,rs1483185,"{'flags': ['cds_end_NF'], 'variant_allele': 'A...",MODIFIER,5.268,0.162378,A,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004699:calc...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,rs1483185,"{'cadd_phred': 5.142, 'impact': 'MODIFIER', 'm...",MODIFIER,5.142,0.154256,G,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004699:calc...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Index(['id', 'consequences', 'impact', 'cadd_phred', 'cadd_raw',
       'variant_allele', 'consequence_terms', 'phenotypes', 'gene_symbol',
       'go', 'transcript_id', 'hgnc_id', 'gene_symbol_source', 'biotype',
       'gene_id', 'strand', 'refseq_transcript_ids', 'flags', 'distance',
       'canonical', 'mastermind_counts', 'mastermind_mmid3', 'polyphen_score',
       'cds_end', 'amino_acids', 'domains', 'cdna_start', 'protein_end',
       'protein_start', 'sift_prediction', 'cdna_end', 'cds_start', 'codons',
       'polyphen_prediction', 'sift_score'],
      dtype='object')

In [12]:
merged_df_all = pd.merge(df_2_all, df, how="left", on="id")
merged_df_all.drop(columns=["input", "seq_region_name"])

,id,consequences,impact,cadd_phred,cadd_raw,variant_allele,consequence_terms,phenotypes,gene_symbol,go,...,vcf_string,colocated_variants,allele_string,strand_y,most_severe_consequence,transcript_consequences,start,variant_class,intergenic_consequences,motif_feature_consequences
0,rs10062536,"{'impact': 'MODIFIER', 'cadd_phred': 7.734, 'c...",MODIFIER,7.734,0.341480,T,[intergenic_variant],NaN,NaN,NaN,...,5-148825669-C-T,"[{'strand': 1, 'id': 'rs10062536', 'seq_region...",C/T,1,intergenic_variant,NaN,148825669,SNV,"[{'impact': 'MODIFIER', 'cadd_phred': 7.734, '...",NaN
1,rs414582,"{'impact': 'MODIFIER', 'cadd_raw': -0.30287, '...",MODIFIER,0.359,-0.302870,C,[intergenic_variant],NaN,NaN,NaN,...,5-148851149-T-C,"[{'minor_allele_freq': 0.1869, 'minor_allele':...",T/C,1,regulatory_region_variant,NaN,148851149,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': -0.30287, ...",NaN
2,rs10061434,"{'impact': 'MODIFIER', 'cadd_raw': -0.059472, ...",MODIFIER,1.828,-0.059472,T,[intergenic_variant],NaN,NaN,NaN,...,5-149023879-C-T,"[{'start': 149023879, 'id': 'rs10061434', 'all...",C/T,1,intergenic_variant,NaN,149023879,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': -0.059472,...",NaN
3,rs10454990,"{'impact': 'MODIFIER', 'cadd_raw': 0.083336, '...",MODIFIER,3.983,0.083336,G,[intergenic_variant],"[{'p_value': 5e-06, 'end': 148838117, 'odds_ra...",NaN,NaN,...,"[5-148838117-C-G, 5-148838117-C-T]","[{'minor_allele_freq': 0.356, 'phenotype_or_di...",C/G/T,1,regulatory_region_variant,NaN,148838117,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': 0.083336, ...",NaN
4,rs72823546,"{'consequence_terms': ['intergenic_variant'], ...",MODIFIER,6.259,0.228896,A,[intergenic_variant],NaN,NaN,NaN,...,"[5-148850866-G-A, 5-148850866-G-C]","[{'strand': 1, 'seq_region_name': '5', 'allele...",G/A/C,1,regulatory_region_variant,NaN,148850866,SNV,"[{'consequence_terms': ['intergenic_variant'],...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,rs1483185,"{'cadd_phred': 5.142, 'impact': 'MODIFIER', 'm...",MODIFIER,5.142,0.154256,G,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004699:calc...",...,"[HG957_PATCH-53199014-T-A, HG957_PATCH-5319901...","[{'start': 53199014, 'seq_region_name': 'HG957...",T/A/G,1,intron_variant,"[{'hgnc_id': 9399, 'gene_symbol': 'PRKCD', 'va...",53199014,SNV,NaN,NaN
603,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,3-53228342-C-T,"[{'start': 53228342, 'seq_region_name': '3', '...",C/T,1,downstream_gene_variant,"[{'cadd_phred': 6.551, 'impact': 'MODIFIER', '...",53228342,SNV,NaN,NaN
604,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,HG957_PATCH-53228342-C-T,"[{'minor_allele_freq': 0.1857, 'id': 'rs729396...",C/T,1,downstream_gene_variant,"[{'variant_allele': 'T', 'gene_symbol': 'PRKCD...",53228342,SNV,NaN,NaN
605,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,3-53228342-C-T,"[{'start': 53228342, 'seq_region_name': '3', '...",C/T,1,downstream_gene_variant,"[{'cadd_phred': 6.551, 'impact': 'MODIFIER', '...",53228342,SNV,NaN,NaN
606,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,HG957_PATCH-53228342-C-T,"[{'minor_allele_freq': 0.1857, 'id': 'rs729396...",C/T,1,downstream_gene_variant,"[{'variant_allele': 'T', 'gene_symbol': 'PRKCD...",53228342,SNV,NaN,NaN

In [38]:
df_uniqued_all = merged_df_all.drop_duplicates(subset=['id', 'cadd_phred', 'variant_allele'])

In [39]:
df_uniqued_all

,id,consequences,impact,cadd_phred,cadd_raw,variant_allele,consequence_terms,phenotypes,gene_symbol,go,...,allele_string,seq_region_name,input,strand_y,most_severe_consequence,transcript_consequences,start,variant_class,intergenic_consequences,motif_feature_consequences
0,rs10062536,"{'impact': 'MODIFIER', 'cadd_phred': 7.734, 'c...",MODIFIER,7.734,0.341480,T,[intergenic_variant],NaN,NaN,NaN,...,C/T,5,rs10062536,1,intergenic_variant,NaN,148825669,SNV,"[{'impact': 'MODIFIER', 'cadd_phred': 7.734, '...",NaN
1,rs414582,"{'impact': 'MODIFIER', 'cadd_raw': -0.30287, '...",MODIFIER,0.359,-0.302870,C,[intergenic_variant],NaN,NaN,NaN,...,T/C,5,rs414582,1,regulatory_region_variant,NaN,148851149,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': -0.30287, ...",NaN
2,rs10061434,"{'impact': 'MODIFIER', 'cadd_raw': -0.059472, ...",MODIFIER,1.828,-0.059472,T,[intergenic_variant],NaN,NaN,NaN,...,C/T,5,rs10061434,1,intergenic_variant,NaN,149023879,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': -0.059472,...",NaN
3,rs10454990,"{'impact': 'MODIFIER', 'cadd_raw': 0.083336, '...",MODIFIER,3.983,0.083336,G,[intergenic_variant],"[{'p_value': 5e-06, 'end': 148838117, 'odds_ra...",NaN,NaN,...,C/G/T,5,rs10454990,1,regulatory_region_variant,NaN,148838117,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': 0.083336, ...",NaN
4,rs72823546,"{'consequence_terms': ['intergenic_variant'], ...",MODIFIER,6.259,0.228896,A,[intergenic_variant],NaN,NaN,NaN,...,G/A/C,5,rs72823546,1,regulatory_region_variant,NaN,148850866,SNV,"[{'consequence_terms': ['intergenic_variant'],...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,rs11924565,"{'cadd_phred': 5.401, 'impact': 'MODIFIER', 'm...",MODIFIER,5.401,0.170975,G,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,C/A/G/T,3,rs11924565,1,intron_variant,"[{'consequence_terms': ['intron_variant'], 'va...",53197640,SNV,NaN,[{'consequence_terms': ['TF_binding_site_varia...
547,rs11924565,"{'strand': 1, 'gene_symbol_source': 'HGNC', 't...",MODIFIER,6.272,0.229776,T,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,C/A/G/T,3,rs11924565,1,intron_variant,"[{'consequence_terms': ['intron_variant'], 'va...",53197640,SNV,NaN,[{'consequence_terms': ['TF_binding_site_varia...
579,rs1483185,"{'impact': 'MODIFIER', 'cadd_phred': 5.268, 'g...",MODIFIER,5.268,0.162378,A,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,T/A/G,3,rs1483185,1,intron_variant,"[{'impact': 'MODIFIER', 'cadd_phred': 5.268, '...",53199014,SNV,NaN,NaN
581,rs1483185,"{'gene_symbol_source': 'HGNC', 'strand': 1, 't...",MODIFIER,5.142,0.154256,G,[intron_variant],"[{'seq_region_name': '3', 'end': 53226733, 'st...",PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,T/A/G,3,rs1483185,1,intron_variant,"[{'impact': 'MODIFIER', 'cadd_phred': 5.268, '...",53199014,SNV,NaN,NaN
603,rs729396,"{'cadd_phred': 6.551, 'impact': 'MODIFIER', 'g...",MODIFIER,6.551,0.249872,T,[downstream_gene_variant],NaN,PRKCD,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,C/T,3,rs729396,1,downstream_gene_variant,"[{'cadd_phred': 6.551, 'impact': 'MODIFIER', '...",53228342,SNV,NaN,NaN

In [40]:
df_uniqued_all.to_csv("./feature_tsv/VEP_noncanonical_included_Output.tsv", sep = '\t', index= False)

Only contain variants from Canoncical transcripts for variants in exons

In [9]:
list_intron = []
list_exon = []
name = ["ENSG00000163932", "ENSG00000162337", "ENSG00000112033", "ENSG00000113712", "ENSG00000135744","ENSG00000105647"]
for i in range(0,len(variant_effect)):
    if "intergenic_consequences" in variant_effect[i].keys():
        list_intron.append((df["id"][i],variant_effect[i]["intergenic_consequences"][0]))
        
    elif "transcript_consequences" in variant_effect[i].keys():
        for dic in variant_effect[i]["transcript_consequences"]:
            if "canonical" in dic and dic["gene_id"] in name:
                list_exon.append((df["id"][i],dic))

complete_list = list_intron + list_exon  
len(complete_list)

153

In [10]:
complete_list

[('rs10062536',
  {'variant_allele': 'T',
   'cadd_raw': 0.34148,
   'cadd_phred': 7.734,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs414582',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'variant_allele': 'C',
   'cadd_raw': -0.30287,
   'cadd_phred': 0.359}),
 ('rs10061434',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'T',
   'cadd_phred': 1.828,
   'cadd_raw': -0.059472}),
 ('rs10454990',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'G',
   'cadd_phred': 3.983,
   'cadd_raw': 0.083336,
   'phenotypes': [{'variation_names': 'rs10454990',
     'odds_ratio': 4.558,
     'p_value': 5e-06,
     'seq_region_name': '5',
     'risk_allele': 'C',
     'id': 'rs10454990',
     'type': 'Variation',
     'associated_gene': 'MIR143HG,CSNK1A1',
     'start': 148838117,
     'source': 'NHGRI-EBI_GWAS_catalog',
     'phenotype': 'Carotid intima media thickness x smoking interaction',
     'end': 148838117,
     'strand': '+'}]}),
 ('rs72823546',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_phred': 6.259,
   'cadd_raw': 0.228896}),
 ('rs353237',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': 0.459367,
   'variant_allele': 'G',
   'cadd_phred': 9.011}),
 ('rs4705346',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': 0.326805,
   'variant_allele': 'A',
   'cadd_phred': 7.554}),
 ('rs11745684',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'T',
   'cadd_raw': -0.069812,
   'cadd_phred': 1.712}),
 ('rs2454104',
  {'cadd_raw': -0.351055,
   'variant_allele': 'A',
   'cadd_phred': 0.257,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs78578633',
  {'variant_allele': 'T',
   'cadd_raw': 0.498089,
   'cadd_phred': 9.385,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs17724303',
  {'variant_allele': 'A',
   'cadd_phred': 1.64,
   'cadd_raw': -0.076466,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs447950',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_phred': 11.29,
   'cadd_raw': 0.717338}),
 ('rs72823547',
  {'variant_allele': 'T',
   'cadd_phred': 5.744,
   'cadd_raw': 0.193563,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs73279543',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': -0.162437,
   'variant_allele': 'G',
   'cadd_phred': 0.924}),
 ('rs452366',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': -0.140876,
   'variant_allele': 'A',
   'cadd_phred': 1.069}),
 ('rs241280',
  {'variant_allele': 'T',
   'cadd_phred': 0.118,
   'cadd_raw': -0.460428,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs353248',
  {'cadd_raw': -0.384941,
   'variant_allele': 'A',
   'cadd_phred': 0.202,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs353243',
  {'cadd_phred': 5.374,
   'variant_allele': 'A',
   'cadd_raw': 0.169239,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs353241',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_raw': -0.141188,
   'cadd_phred': 1.067}),
 ('rs62378023',
  {'cadd_phred': 4.452,
   'variant_allele': 'T',
   'cadd_raw': 0.111457,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs118050745',
  {'cadd_raw': -0.174227,
   'variant_allele': 'C',
   'cadd_phred': 0.853,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs113800014',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_phred': 0.788,
   'variant_allele': 'T',
   'cadd_raw': -0.186207}),
 ('rs11602367',
  {'cadd_raw': -0.050675,
   'variant_allele': 'C',
   'cadd_phred': 1.932,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant']}),
 ('rs474742',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_raw': 0.050944,
   'variant_allele': 'A',
   'cadd_phred': 3.44}),
 ('rs4713858',
  {'cadd_phred': 2.07,
   'variant_allele': 'G',
   'phenotypes': [{'strand': '+',
     'end': 35402785,
     'phenotype': 'Height',
     'associated_gene': 'ANKS1A,TCP11,ZNF76,DEF6,SCUBE3',
     'source': 'NHGRI-EBI_GWAS_catalog',
     'start': 35402785,
     'id': 'rs4713858',
     'type': 'Variation',
     'risk_allele': 'G',
     'odds_ratio': 6.8,
     'seq_region_name': '6',
     'p_value': 4e-08,
     'variation_names': 'rs4713858'}],
   'cadd_raw': -0.039583,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs6457821',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'variant_allele': 'A',
   'phenotypes': [{'risk_allele': 'C',
     'type': 'Variation',
     'id': 'rs6457821',
     'strand': '+',
     'source': 'GIANT',
     'start': 35402805,
     'seq_region_name': '6',
     'p_value': 1.823e-11,
     'end': 35402805,
     'phenotype': 'Height'},
    {'beta_coef': '0.104 unit decrease',
     'strand': '+',
     'start': 35402805,
     'source': 'NHGRI-EBI_GWAS_catalog',
     'associated_gene': 'PPARD/FANCE',
     'phenotype': 'Height',
     'end': 35402805,
     'risk_allele': 'A',
     'type': 'Variation',
     'id': 'rs6457821',
     'variation_names': 'rs6457821',
     'p_value': 2e-12,
     'seq_region_name': '6'}],
   'cadd_raw': 0.044029,
   'cadd_phred': 3.325}),
 ('rs115269427',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A',
   'cadd_raw': -0.136784,
   'cadd_phred': 1.099}),
 ('rs78945013',
  {'variant_allele': 'T',
   'cadd_raw': -0.077146,
   'cadd_phred': 1.633,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs853469',
  {'cadd_phred': 2.187,
   'variant_allele': 'C',
   'consequence_terms': ['intergenic_variant'],
   'cadd_raw': -0.03063,
   'phenotypes': [{'p_value': 5.491e-05,
     'type': 'Variation',
     'start': 230759310,
     'seq_region_name': '1',
     'associated_gene': 'RPS24P4,COG2',
     'end': 230759310,
     'phenotype': 'Body Mass Index',
     'id': 'rs853469',
     'source': 'dbGaP',
     'strand': '+',
     'variation_names': 'rs853469'}],
   'impact': 'MODIFIER'}),
 ('rs12031571',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'cadd_raw': -0.019374,
   'variant_allele': 'A',
   'cadd_phred': 2.342}),
 ('rs77645389',
  {'variant_allele': 'T',
   'cadd_phred': 1.201,
   'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'cadd_raw': -0.123666}),
 ('rs4846997',
  {'cadd_raw': -0.117906,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_phred': 1.248,
   'variant_allele': 'A'}),
 ('rs11122563',
  {'cadd_raw': 0.032074,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_phred': 3.128,
   'variant_allele': 'C'}),
 ('rs11122562',
  {'variant_allele': 'A',
   'cadd_phred': 1.263,
   'cadd_raw': -0.11617,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs62120362',
  {'cadd_raw': -0.053287,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_phred': 1.901,
   'variant_allele': 'C'}),
 ('rs115659375',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'cadd_raw': -0.318184,
   'cadd_phred': 0.323,
   'variant_allele': 'A'}),
 ('rs115659375',
  {'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'variant_allele': 'A'}),
 ('rs11919522',
  {'variant_allele': 'C',
   'cadd_phred': 3.361,
   'impact': 'MODIFIER',
   'cadd_raw': 0.046178,
   'consequence_terms': ['intergenic_variant']}),
 ('rs11919522',
  {'variant_allele': 'C',
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs115657945',
  {'variant_allele': 'T',
   'cadd_phred': 8.324,
   'cadd_raw': 0.393143,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs79843306',
  {'variant_allele': 'A',
   'cadd_phred': 0.305,
   'cadd_raw': -0.326153,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER'}),
 ('rs79843306',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'variant_allele': 'A'}),
 ('rs116071986',
  {'cadd_raw': 0.147698,
   'consequence_terms': ['intergenic_variant'],
   'impact': 'MODIFIER',
   'cadd_phred': 5.038,
   'variant_allele': 'A'}),
 ('rs7610701',
  {'impact': 'MODIFIER',
   'consequence_terms': ['intergenic_variant'],
   'cadd_raw': 0.116617,
   'variant_allele': 'A',
   'cadd_phred': 4.537}),
 ('rs1080500',
  {'variant_allele': 'A',
   'cadd_phred': 12.37,
   'impact': 'MODIFIER',
   'cadd_raw': 0.853995,
   'consequence_terms': ['intergenic_variant'],
   'phenotypes': [{'associated_gene': 'GLT8D1,GNL3,ITIH1,ITIH3,ITIH4,ITIH4-AS1,MIR8064,MUSTN1,NEK4,NT5DC2,PBRM1,RFT1,SFMBT1,SMIM4,SNORD136,SNORD19,SNORD19B,SNORD69,SPCS1,STAB1,TMEM110,TMEM110-MUSTN1',
     'odds_ratio': 1.0638298,
     'source': 'NHGRI-EBI_GWAS_catalog',
     'phenotype': 'Autism spectrum disorder or schizophrenia',
     'id': 'rs1080500',
     'strand': '+',
     'end': 53175017,
     'variation_names': 'rs1080500',
     'type': 'Variation',
     'p_value': 6e-09,
     'start': 53175017,
     'seq_region_name': '3'}]}),
 ('rs2125130',
  {'gene_id': 'ENSG00000113712',
   'strand': -1,
   'biotype': 'protein_coding',
   'hgnc_id': 2451,
   'consequence_terms': ['intron_variant'],
   'gene_symbol_source': 'HGNC',
   'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'variant_allele': 'A',
   'cadd_phred': 0.469,
   'canonical': 1,
   'impact': 'MODIFIER',
   'transcript_id': 'ENST00000515768',
   'cadd_raw': -0.26352,
   'gene_symbol': 'CSNK1A1'}),
 ('rs111416523',
  {'gene_id': 'ENSG00000113712',
   'biotype': 'protein_coding',
   'strand': -1,
   'consequence_terms': ['intron_variant'],
   'gene_symbol_source': 'HGNC',
   'hgnc_id': 2451,
   'variant_allele': 'C',
   'cadd_phred': 1.749,
   'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'canonical': 1,
   'transcript_id': 'ENST00000515768',
   'impact': 'MODIFIER',
   'cadd_raw': -0.06643,
   'gene_symbol': 'CSNK1A1'}),
 ('rs114688286',
  {'cadd_raw': 0.123768,
   'gene_symbol': 'CSNK1A1',
   'impact': 'MODIFIER',
   'transcript_id': 'ENST00000515768',
   'go': 'GO:0000777:condensed_chromosome_kinetochore,GO:0004672:protein_kinase_activity,GO:0004674:protein_serine/threonine_kinase_activity,GO:0005515:protein_binding,GO:0005524:ATP_binding,GO:0005813:centrosome,GO:0005829:cytosol,GO:0005847:mRNA_cleavage_and_polyadenylation_specificity_factor_complex,GO:0006468:protein_phosphorylation,GO:0007067:mitosis,GO:0007165:signal_transduction,GO:0007166:cell_surface_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0016607:nuclear_speck,GO:0016772:transferase_activity_-_transferring_phosphorus-containing_groups',
   'cadd_phred': 4.654,
   'variant_allele': 'G',
   'canonical': 1,
   'gene_id': 'ENSG00000113712',
   'biotype': 'protein_coding',
   'strand': -1,
   'hgnc_id': 2451,
   'gene_symbol_source': 'HGNC',
   'consequence_terms': ['intron_variant']}),
 ('rs599083',
  {'consequence_terms': ['intron_variant'],
   'hgnc_id': 6697,
   'mastermind_counts': '49|49|54',
   'gene_id': 'ENSG00000162337',
   'mastermind_mmid3': 'LRP5:G1079int,LRP5:G1079inta,LRP5:G498int,LRP5:G498inta',
   'biotype': 'protein_coding',
   'canonical': 1,
   'cadd_phred': 3.135,
   'variant_allele': 'G',
   'go': 'GO:0001702:gastrulation_with_mouth_forming_second,GO:0001944:vasculature_development,GO:0002053:positive_regulation_of_mesenchymal_cell_proliferation,GO:0002076:osteoblast_development,GO:0005515:protein_binding,GO:0005739:mitochondrion,GO:0005783:endoplasmic_reticulum,GO:0005886:plasma_membrane,GO:0006007:glucose_catabolic_process,GO:0006897:endocytosis,GO:0008203:cholesterol_metabolic_process,GO:0008217:regulation_of_blood_pressure,GO:0008284:positive_regulation_of_cell_proliferation,GO:0009952:anterior/posterior_pattern_specification,GO:0015026:coreceptor_activity,GO:0016021:integral_component_of_membrane,GO:0016055:Wnt_receptor_signaling_pathway,GO:0016055:Wnt_signaling_pathway,GO:0017147:Wnt-protein_binding,GO:0030326:embryonic_limb_morphogenesis,GO:0033690:positive_regulation_of_osteoblast_proliferation,GO:0035019:somatic_stem_cell_maintenance,GO:0035108:limb_morphogenesis,GO:0035426:extracellular_matrix-cell_signaling,GO:0042074:cell_migration_involved_in_gastrulation,GO:0042632:cholesterol_homeostasis,GO:0042733:embryonic_digit_morphogenesis,GO:0042813:Wnt-activated_receptor_activity,GO:0042981:regulation_of_apoptotic_process,GO:0043235:receptor_complex,GO:0043434:response_to_peptide_hormone_stimulus,GO:0044332:Wnt_signaling_pathway_involved_in_dorsal/ventral_axis_specification,GO:0045600:positive_regulation_of_fat_cell_differentiation,GO:0045668:negative_regulation_of_osteoblast_differentiation,GO:0045840:positive_regulation_of_mitosis,GO:0045893:positive_regulation_of_transcription_-_DNA-dependent,GO:0045893:positive_regulation_of_transcription_-_DNA-templated,GO:0045944:positive_regulation_of_transcription_from_RNA_polymerase_II_promoter,GO:0046849:bone_remodeling,GO:0046850:regulation_of_bone_remodeling,GO:0048539:bone_marrow_development,GO:0048596:embryonic_camera-type_eye_morphogenesis,GO:0051091:positive_regulation_of_sequence-specific_DNA_binding_transcription_factor_activity,GO:0060033:anatomical_structure_regression,GO:0060042:retina_morphogenesis_in_camera-type_eye,GO:0060059:embryonic_retina_morphogenesis_in_camera-type_eye,GO:0060070:canonical_Wnt_receptor_signaling_pathway,GO:0060070:canonical_Wnt_signaling_pathway,GO:0060348:bone_development,GO:0060349:bone_morphogenesis,GO:0060444:branching_involved_in_mammary_gland_duct_morphogenesis,GO:0060603:mammary_gland_duct_morphogenesis,GO:0060612:adipose_tissue_development,GO:0060764:cell-cell_signaling_involved_in_mammary_gland_development,GO:0060828:regulation_of_canonical_Wnt_signaling_pathway,GO:0061178:regulation_of_insulin_secretion_involved_in_cellular_response_to_glucose_stimulus,GO:0061299:retina_vasculature_morphogenesis_in_camera-type_eye,GO:0061304:retinal_blood_vessel_morphogenesis,GO:0071901:negative_regulation_of_protein_serine/threonine_kinase_activity,GO:1902262:apoptotic_process_involved_in_patterning_of_blood_vessels',
   'phenotypes': [{'start': 68080077,
     'inheritance_type': 'monoallelic',
     'source': 'DDG2P',
     'phenotype': 'ENDOSTEAL HYPEROSTOSIS WORTH TYPE',
     'end': 68216743,
     'seq_region_name': '11',
     'id': 'ENSG00000162337',
     'strand': '+',
     'external_id': 144750,
     'type': 'Gene'},
    {'end': 68216743,
     'phenotype': 'HIGH BONE MASS TRAIT',
     'seq_region_name': '11',
     'source': 'DDG2P',
     'inheritance_type': 'monoallelic',
     'start': 68080077,
     'external_id': 601884,
     'id': 'ENSG00000162337',
     'strand': '+',
     'type': 'Gene'},
    {'external_id': 607634,
     'strand': '+',
     'id': 'ENSG00000162337',
     'type': 'Gene',
     'end': 68216743,
     'phenotype': 'Osteopetrosis autosomal dominant type 1',
     'seq_region_name': '11',
     'inheritance_type': 'monoallelic',
     'source': 'DDG2P',
     'start': 68080077},
    {'end': 68216743,
     'phenotype': 'OSTEOPOROSIS-PSEUDOGLIOMA SYNDROME',
     'seq_region_name': '11',
     'inheritance_type': 'biallelic',
     'source': 'DDG2P',
     'start': 68080077,
     'external_id': 259770,
     'id': 'ENSG00000162337',
     'strand': '+',
     'type': 'Gene'},
    {'start': 68080077,
     'inheritance_type': 'monoallelic',
     'source': 'DDG2P',
     'phenotype': 'VITREORETINOPATHY EXUDATIVE TYPE 4',
     'end': 68216743,
     'seq_region_name': '11',
     'id': 'ENSG00000162337',
     'strand': '+',
     'external_id': 601813,
     'type': 'Gene'},
    {'id': 'ENSG00000162337',
     'strand': '+',
     'external_id': 601884,
     'type': 'Gene',
     'phenotype': 'Bone mineral density quantitative trait locus 1',
     'end': 68216743,
     'seq_region_name': '11',
     'attrib_type': 'Gene',
     'start': 68080077,
     'source': 'MIM_morbid'},
    {'end': 68216743,
     'phenotype': 'Exudative vitreoretinopathy 4',
     'attrib_type': 'Gene',
     'seq_region_name': '11',
     'source': 'MIM_morbid',
     'start': 68080077,
     'external_id': 601813,
     'strand': '+',
     'id': 'ENSG00000162337',
     'type': 'Gene'},
    {'attrib_type': 'Gene',
     'seq_region_name': '11',
     'end': 68216743,
     'phenotype': 'HYPEROSTOSIS CORTICALIS GENERALISATA, BENIGN FORM OF WORTH, WITH TORUS',
     'source': 'MIM_morbid',
     'start': 68080077,
     'type': 'Gene',
     'external_id': 144750,
     'strand': '+',
     'id': 'ENSG00000162337'},
    {'start': 68080077,
     'source': 'MIM_morbid',
     'seq_region_name': '11',
     'attrib_type': 'Gene',
     'phenotype': 'OSTEOPETROSIS, AUTOSOMAL DOMINANT 1',
     'end': 68216743,
     'type': 'Gene',
     'strand': '+',
     'id': 'ENSG00000162337',
     'external_id': 607634},
    {'type': 'Gene',
     'strand': '+',
     'id': 'ENSG00000162337',
     'external_id': 166710,
     'start': 68080077,
     'source': 'MIM_morbid',
     'seq_region_name': '11',
     'attrib_type': 'Gene',
     'phenotype': 'OSTEOPOROSIS',
     'end': 68216743},
    {'start': 68080077,
     'source': 'MIM_morbid',
     'phenotype': 'OSTEOPOROSIS-PSEUDOGLIOMA SYNDROME',
     'end': 68216743,
     'seq_region_name': '11',
     'attrib_type': 'Gene',
     'strand': '+',
     'id': 'ENSG00000162337',
     'external_id': 259770,
     'type': 'Gene'},
    {'type': 'Gene',
     'strand': '+',
     'id': 'ENSG00000162337',
     'external_id': 607636,
     'seq_region_name': '11',
     'attrib_type': 'Gene',
     'phenotype': 'Van Buchem disease type 2',
     'end': 68216743,
     'start': 68080077,
     'source': 'MIM_morbid'},
    {'type': 'Gene',
     'strand': '+',
     'id': 'ENSG00000162337',
     'external_id': 2783,
     'start': 68080077,
     'source': 'Orphanet',
     'seq_region_name': '11',
     'phenotype': 'Autosomal dominant osteopetrosis type 1',
     'end': 68216743},
    {'type': 'Gene',
     'external_id': 2790,
     'id': 'ENSG00000162337',
     'strand': '+',
     'seq_region_name': '11',
     'end': 68216743,
     'phenotype': 'Endosteal hyperostosis, Worth type',
     'source': 'Orphanet',
     'start': 68080077},
    {'source': 'Orphanet',
     'start': 68080077,
     'seq_region_name': '11',
     'end': 68216743,
     'phenotype': 'Familial exudative vitreoretinopathy',
     'type': 'Gene',
     'external_id': 891,

In [63]:
df_2 = pd.DataFrame(complete_list, columns = ["id","consequences"])
expanded_df = df_2["consequences"].apply(pd.Series)
df_2 = pd.concat([df_2, expanded_df], axis=1)

In [64]:
df_2.columns

Index(['id', 'consequences', 'cadd_raw', 'variant_allele', 'cadd_phred',
       'consequence_terms', 'impact', 'phenotypes', 'biotype', 'gene_id', 'go',
       'transcript_id', 'canonical', 'strand', 'gene_symbol_source',
       'gene_symbol', 'hgnc_id', 'mastermind_counts', 'mastermind_mmid3',
       'refseq_transcript_ids', 'polyphen_score', 'cds_end', 'sift_prediction',
       'protein_end', 'amino_acids', 'domains', 'codons', 'cdna_start',
       'protein_start', 'cds_start', 'cdna_end', 'sift_score',
       'polyphen_prediction', 'distance'],
      dtype='object')

In [66]:
df_2

,id,consequences,cadd_raw,variant_allele,cadd_phred,consequence_terms,impact,phenotypes,biotype,gene_id,...,amino_acids,domains,codons,cdna_start,protein_start,cds_start,cdna_end,sift_score,polyphen_prediction,distance
0,rs10062536,"{'cadd_raw': 0.34148, 'variant_allele': 'T', '...",0.341480,T,7.734,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,rs414582,"{'impact': 'MODIFIER', 'cadd_raw': -0.30287, '...",-0.302870,C,0.359,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,rs10061434,"{'impact': 'MODIFIER', 'cadd_phred': 1.828, 'v...",-0.059472,T,1.828,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,rs10454990,"{'phenotypes': [{'end': 148838117, 'p_value': ...",0.083336,G,3.983,[intergenic_variant],MODIFIER,"[{'end': 148838117, 'p_value': 5e-06, 'seq_reg...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,rs72823546,"{'variant_allele': 'A', 'cadd_phred': 6.259, '...",0.228896,A,6.259,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,rs11924565,"{'biotype': 'protein_coding', 'consequence_ter...",0.170975,G,5.401,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,rs11924565,"{'consequence_terms': ['intron_variant'], 'bio...",0.229776,T,6.272,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,rs1483185,"{'mastermind_mmid3': 'PRKCD:5UTR,PRKCD:5UTRint...",0.162378,A,5.268,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,rs1483185,"{'gene_symbol_source': 'HGNC', 'variant_allele...",0.154256,G,5.142,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,rs729396,"{'go': 'GO:0001666:response_to_hypoxia,GO:0004...",0.249872,T,6.551,[downstream_gene_variant],MODIFIER,NaN,protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1609.0

In [61]:
# merged_df = pd.merge(df_2, df, how="left", on="id")
# merged_df.drop(columns=["input", "seq_region_name"])

,id,consequences,cadd_raw,variant_allele,cadd_phred,consequence_terms,impact,phenotypes,biotype,gene_id,...,colocated_variants,most_severe_consequence,vcf_string,end,assembly_name,regulatory_feature_consequences,allele_string,variant_class,intergenic_consequences,motif_feature_consequences
0,rs10062536,"{'cadd_raw': 0.34148, 'variant_allele': 'T', '...",0.341480,T,7.734,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,"[{'minor_allele_freq': 0.1953, 'strand': 1, 'e...",intergenic_variant,5-148825669-C-T,148825669,GRCh37,NaN,C/T,SNV,"[{'cadd_raw': 0.34148, 'variant_allele': 'T', ...",NaN
1,rs414582,"{'impact': 'MODIFIER', 'cadd_raw': -0.30287, '...",-0.302870,C,0.359,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,"[{'start': 148851149, 'minor_allele': 'C', 'id...",regulatory_region_variant,5-148851149-T-C,148851149,GRCh37,[{'consequence_terms': ['regulatory_region_var...,T/C,SNV,"[{'impact': 'MODIFIER', 'cadd_raw': -0.30287, ...",NaN
2,rs10061434,"{'impact': 'MODIFIER', 'cadd_phred': 1.828, 'v...",-0.059472,T,1.828,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,"[{'allele_string': 'C/T', 'minor_allele_freq':...",intergenic_variant,5-149023879-C-T,149023879,GRCh37,NaN,C/T,SNV,"[{'impact': 'MODIFIER', 'cadd_phred': 1.828, '...",NaN
3,rs10454990,"{'phenotypes': [{'end': 148838117, 'p_value': ...",0.083336,G,3.983,[intergenic_variant],MODIFIER,"[{'end': 148838117, 'p_value': 5e-06, 'seq_reg...",NaN,NaN,...,"[{'phenotype_or_disease': 1, 'pubmed': [321174...",regulatory_region_variant,"[5-148838117-C-G, 5-148838117-C-T]",148838117,GRCh37,[{'consequence_terms': ['regulatory_region_var...,C/G/T,SNV,"[{'phenotypes': [{'end': 148838117, 'p_value':...",NaN
4,rs72823546,"{'variant_allele': 'A', 'cadd_phred': 6.259, '...",0.228896,A,6.259,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,"[{'allele_string': 'G/A/C', 'end': 148850866, ...",regulatory_region_variant,"[5-148850866-G-A, 5-148850866-G-C]",148850866,GRCh37,"[{'regulatory_feature_id': 'ENSR00000188817', ...",G/A/C,SNV,"[{'variant_allele': 'A', 'cadd_phred': 6.259, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,rs1483185,"{'mastermind_mmid3': 'PRKCD:5UTR,PRKCD:5UTRint...",0.162378,A,5.268,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,"[{'allele_string': 'T/A/G', 'strand': 1, 'seq_...",intron_variant,"[HG957_PATCH-53199014-T-A, HG957_PATCH-5319901...",53199014,GRCh37,NaN,T/A/G,SNV,NaN,NaN
170,rs1483185,"{'gene_symbol_source': 'HGNC', 'variant_allele...",0.154256,G,5.142,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,"[{'id': 'rs1483185', 'start': 53199014, 'pubme...",intron_variant,"[3-53199014-T-A, 3-53199014-T-G]",53199014,GRCh37,"[{'biotype': 'CTCF_binding_site', 'cadd_phred'...",T/A/G,SNV,NaN,NaN
171,rs1483185,"{'gene_symbol_source': 'HGNC', 'variant_allele...",0.154256,G,5.142,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,"[{'allele_string': 'T/A/G', 'strand': 1, 'seq_...",intron_variant,"[HG957_PATCH-53199014-T-A, HG957_PATCH-5319901...",53199014,GRCh37,NaN,T/A/G,SNV,NaN,NaN
172,rs729396,"{'go': 'GO:0001666:response_to_hypoxia,GO:0004...",0.249872,T,6.551,[downstream_gene_variant],MODIFIER,NaN,protein_coding,ENSG00000163932,...,"[{'allele_string': 'C/T', 'frequencies': {'T':...",downstream_gene_variant,3-53228342-C-T,53228342,GRCh37,NaN,C/T,SNV,NaN,NaN
173,rs729396,"{'go': 'GO:0001666:response_to_hypoxia,GO:0004...",0.249872,T,6.551,[downstream_gene_variant],MODIFIER,NaN,protein_coding,ENSG00000163932,...,"[{'id': 'rs729396', 'start': 53228342, 'minor_...",downstream_gene_variant,HG957_PATCH-53228342-C-T,53228342,GRCh37,NaN,C/T,SNV,NaN,NaN

In [16]:
df_unique = df[~df['id'].duplicated(keep="first")]
df_unique = df_unique[["id","allele_string", "vcf_string"]]

In [17]:
df_unique

             id allele_string                        vcf_string
0      rs353294           A/C                   5-148802811-A-C
1    rs77489920           A/G                   5-149001897-A-G
2     rs3733658           G/A                   5-149012782-G-A
3     rs1379544           T/C                   5-148981046-T-C
4    rs10062536           C/T                   5-148825669-C-T
..          ...           ...                               ...
317  rs75323042         T/C/G  [3-53139644-T-C, 3-53139644-T-G]
318   rs4687718         A/G/T  [3-53282303-A-G, 3-53282303-A-T]
320   rs2564921           T/C                    3-53125585-T-C
321   rs1004807           T/C                    3-53140603-T-C
322   rs6799185           C/T                    3-53101580-C-T

[301 rows x 3 columns]

In [156]:
vep = pd.merge(df_2, df_unique, on = "id", how="left")

In [157]:
vep

,id,consequences,cadd_raw,variant_allele,cadd_phred,consequence_terms,impact,phenotypes,biotype,gene_id,...,codons,cdna_start,protein_start,cds_start,cdna_end,sift_score,polyphen_prediction,distance,allele_string,vcf_string
0,rs10062536,"{'cadd_raw': 0.34148, 'variant_allele': 'T', '...",0.341480,T,7.734,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/T,5-148825669-C-T
1,rs414582,"{'impact': 'MODIFIER', 'cadd_raw': -0.30287, '...",-0.302870,C,0.359,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T/C,5-148851149-T-C
2,rs10061434,"{'impact': 'MODIFIER', 'cadd_phred': 1.828, 'v...",-0.059472,T,1.828,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/T,5-149023879-C-T
3,rs10454990,"{'phenotypes': [{'end': 148838117, 'p_value': ...",0.083336,G,3.983,[intergenic_variant],MODIFIER,"[{'end': 148838117, 'p_value': 5e-06, 'seq_reg...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/G/T,"[5-148838117-C-G, 5-148838117-C-T]"
4,rs72823546,"{'variant_allele': 'A', 'cadd_phred': 6.259, '...",0.228896,A,6.259,[intergenic_variant],MODIFIER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G/A/C,"[5-148850866-G-A, 5-148850866-G-C]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,rs11924565,"{'biotype': 'protein_coding', 'consequence_ter...",0.170975,G,5.401,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/A/G/T,"[3-53197640-C-A, 3-53197640-C-G, 3-53197640-C-T]"
149,rs11924565,"{'consequence_terms': ['intron_variant'], 'bio...",0.229776,T,6.272,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/A/G/T,"[3-53197640-C-A, 3-53197640-C-G, 3-53197640-C-T]"
150,rs1483185,"{'mastermind_mmid3': 'PRKCD:5UTR,PRKCD:5UTRint...",0.162378,A,5.268,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T/A/G,"[3-53199014-T-A, 3-53199014-T-G]"
151,rs1483185,"{'gene_symbol_source': 'HGNC', 'variant_allele...",0.154256,G,5.142,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T/A/G,"[3-53199014-T-A, 3-53199014-T-G]"
152,rs729396,"{'go': 'GO:0001666:response_to_hypoxia,GO:0004...",0.249872,T,6.551,[downstream_gene_variant],MODIFIER,NaN,protein_coding,ENSG00000163932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1609.0,C/T,3-53228342-C-T

In [158]:
vep["variant"] = vep["allele_string"].str[0] + '/' + vep["variant_allele"]
vep = vep.drop(columns=["consequences"])
vep

,id,cadd_raw,variant_allele,cadd_phred,consequence_terms,impact,phenotypes,biotype,gene_id,go,...,cdna_start,protein_start,cds_start,cdna_end,sift_score,polyphen_prediction,distance,allele_string,vcf_string,variant
0,rs10062536,0.341480,T,7.734,[intergenic_variant],MODIFIER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/T,5-148825669-C-T,C/T
1,rs414582,-0.302870,C,0.359,[intergenic_variant],MODIFIER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T/C,5-148851149-T-C,T/C
2,rs10061434,-0.059472,T,1.828,[intergenic_variant],MODIFIER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/T,5-149023879-C-T,C/T
3,rs10454990,0.083336,G,3.983,[intergenic_variant],MODIFIER,"[{'end': 148838117, 'p_value': 5e-06, 'seq_reg...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/G/T,"[5-148838117-C-G, 5-148838117-C-T]",C/G
4,rs72823546,0.228896,A,6.259,[intergenic_variant],MODIFIER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G/A/C,"[5-148850866-G-A, 5-148850866-G-C]",G/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,rs11924565,0.170975,G,5.401,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/A/G/T,"[3-53197640-C-A, 3-53197640-C-G, 3-53197640-C-T]",C/G
149,rs11924565,0.229776,T,6.272,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C/A/G/T,"[3-53197640-C-A, 3-53197640-C-G, 3-53197640-C-T]",C/T
150,rs1483185,0.162378,A,5.268,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T/A/G,"[3-53199014-T-A, 3-53199014-T-G]",T/A
151,rs1483185,0.154256,G,5.142,[intron_variant],MODIFIER,"[{'strand': '+', 'seq_region_name': '3', 'end'...",protein_coding,ENSG00000163932,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T/A/G,"[3-53199014-T-A, 3-53199014-T-G]",T/G
152,rs729396,0.249872,T,6.551,[downstream_gene_variant],MODIFIER,NaN,protein_coding,ENSG00000163932,"GO:0001666:response_to_hypoxia,GO:0004672:prot...",...,NaN,NaN,NaN,NaN,NaN,NaN,1609.0,C/T,3-53228342-C-T,C/T

In [ ]:
vep["chr"] = vep["vcf_string"].astype(str).str[0]
type(vep["chr"])

In [150]:
for chrom, group in vep.groupby("chr"):
    print(chrom,":",group["id"].tolist())

1 : ['rs118050745', 'rs113800014', 'rs11602367', 'rs474742', 'rs853469', 'rs77645389', 'rs62120362', 'rs599083', 'rs72932379', 'rs111489476', 'rs11826287', 'rs3781590', 'rs118062233', 'rs35388122', 'rs632605', 'rs118098503', 'rs76710454', 'rs3736228', 'rs75177427', 'rs11574424', 'rs4988300', 'rs3781586', 'rs12417014', 'rs4988332', 'rs75210709', 'rs2306862', 'rs943581', 'rs2067853', 'rs5049', 'rs699', 'rs11122577', 'rs11568048', 'rs7079', 'rs10864772', 'rs2493131', 'rs4762', 'rs3730179', 'rs11554159']
3 : ['rs115657945', 'rs79843306', 'rs79843306', 'rs116071986', 'rs1080500', 'rs750527', 'rs73091425', 'rs11130350', 'rs114058530', 'rs73076230', 'rs729396']
5 : ['rs10062536', 'rs414582', 'rs10061434', 'rs4705346', 'rs11745684', 'rs78578633', 'rs17724303', 'rs72823547', 'rs73279543', 'rs452366', 'rs241280', 'rs62378023', 'rs2125130', 'rs111416523', 'rs114688286']
6 : ['rs6457821', 'rs115269427', 'rs78945013', 'rs2267665', 'rs115128769', 'rs116213531', 'rs9462081', 'rs7770619', 'rs6937510', 'rs9658105', 'rs3734254', 'rs7744392', 'rs9658119', 'rs34474204', 'rs6911817', 'rs72911076', 'rs11751895', 'rs9658130', 'rs67056409', 'rs7771323', 'rs3798343', 'rs6910489', 'rs6457816', 'rs9658058']
[ : ['rs10454990', 'rs72823546', 'rs353237', 'rs2454104', 'rs447950', 'rs353248', 'rs353243', 'rs353241', 'rs4713858', 'rs12031571', 'rs4846997', 'rs11122563', 'rs11122562', 'rs115659375', 'rs115659375', 'rs11919522', 'rs11919522', 'rs7610701', 'rs660925', 'rs660925', 'rs660925', 'rs57928864', 'rs57928864', 'rs4988321', 'rs4988321', 'rs312009', 'rs312009', 'rs634008', 'rs634008', 'rs634008', 'rs314750', 'rs314750', 'rs1883322', 'rs1883322', 'rs1883322', 'rs2016520', 'rs2016520', 'rs4713854', 'rs4713854', 'rs1003973', 'rs1003973', 'rs1003973', 'rs7758272', 'rs7758272', 'rs9658134', 'rs9658134', 'rs6457813', 'rs6457813', 'rs5051', 'rs5051', 'rs5051', 'rs11122576', 'rs11122576', 'rs11122576', 'rs3889728', 'rs3889728', 'rs7630325', 'rs7630325', 'rs111501004', 'rs111501004', 'rs11924565', 'rs11924565', 'rs11924565', 'rs1483185', 'rs1483185']

In [153]:
l = ['rs118050745', 'rs113800014', 'rs11602367', 'rs474742', 'rs853469', 'rs77645389', 'rs62120362', 'rs599083', 'rs72932379', 'rs111489476', 'rs11826287', 'rs3781590', 'rs118062233', 'rs35388122', 'rs632605', 'rs118098503', 'rs76710454', 'rs3736228', 'rs75177427', 'rs11574424', 'rs4988300', 'rs3781586', 'rs12417014', 'rs4988332', 'rs75210709', 'rs2306862', 'rs943581', 'rs2067853', 'rs5049', 'rs699', 'rs11122577', 'rs11568048', 'rs7079', 'rs10864772', 'rs2493131', 'rs4762', 'rs3730179', 'rs11554159']
for i in l:
    print (i)

rs118050745
rs113800014
rs11602367
rs474742
rs853469
rs77645389
rs62120362
rs599083
rs72932379
rs111489476
rs11826287
rs3781590
rs118062233
rs35388122
rs632605
rs118098503
rs76710454
rs3736228
rs75177427
rs11574424
rs4988300
rs3781586
rs12417014
rs4988332
rs75210709
rs2306862
rs943581
rs2067853
rs5049
rs699
rs11122577
rs11568048
rs7079
rs10864772
rs2493131
rs4762
rs3730179
rs11554159

In [121]:
print("\n".join(vep["id"].astype(str)))

rs10062536
rs414582
rs10061434
rs10454990
rs72823546
rs353237
rs4705346
rs11745684
rs2454104
rs78578633
rs17724303
rs447950
rs72823547
rs73279543
rs452366
rs241280
rs353248
rs353243
rs353241
rs62378023
rs118050745
rs113800014
rs11602367
rs474742
rs4713858
rs6457821
rs115269427
rs78945013
rs853469
rs12031571
rs77645389
rs4846997
rs11122563
rs11122562
rs62120362
rs115659375
rs115659375
rs11919522
rs11919522
rs115657945
rs79843306
rs79843306
rs116071986
rs7610701
rs1080500
rs2125130
rs111416523
rs114688286
rs599083
rs72932379
rs111489476
rs11826287
rs3781590
rs660925
rs660925
rs660925
rs118062233
rs57928864
rs57928864
rs4988321
rs4988321
rs35388122
rs632605
rs118098503
rs312009
rs312009
rs76710454
rs3736228
rs75177427
rs11574424
rs4988300
rs3781586
rs634008
rs634008
rs634008
rs12417014
rs314750
rs314750
rs4988332
rs75210709
rs2306862
rs1883322
rs1883322
rs1883322
rs2267665
rs2016520
rs2016520
rs115128769
rs116213531
rs4713854
rs4713854
rs1003973
rs1003973
rs1003973
rs9462081
rs7770619
rs7758272
rs7758272
rs6937510
rs9658105
rs3734254
rs7744392
rs9658119
rs34474204
rs6911817
rs72911076
rs11751895
rs9658130
rs67056409
rs7771323
rs3798343
rs6910489
rs9658134
rs9658134
rs6457813
rs6457813
rs6457816
rs9658058
rs943581
rs5051
rs5051
rs5051
rs2067853
rs5049
rs699
rs11122576
rs11122576
rs11122576
rs11122577
rs11568048
rs3889728
rs3889728
rs7079
rs10864772
rs2493131
rs4762
rs3730179
rs11554159
rs750527
rs7630325
rs7630325
rs73091425
rs11130350
rs111501004
rs111501004
rs114058530
rs73076230
rs11924565
rs11924565
rs11924565
rs1483185
rs1483185
rs729396

In [108]:
vep.to_csv("VEP_Output.tsv", sep = '\t', index= False)

In [15]:
myclient = pymongo.MongoClient("mongodb://localhost:27017")
db = myclient["variantDatabase"]
col = db["transcript_consequences"]